package com.finallion.artificialfoliage.compatibilty.Traverse;

import com.finallion.artificialfoliage.block.*;
import com.finallion.artificialfoliage.registry.ARFOBlocks;
import net.minecraft.block.Block;

public class TraverseBlocks {
    public static void registerBlocks() { }

    public static final Block TRAVERSE_LUSH_SWAMP_WATER = ARFOBlocks.createFluidBlock(TraverseFluids.STILL_TRAVERSE_LUSH_SWAMP_WATER, "traverse_lush_swamp_water");
    public static final Block TRAVERSE_MINI_JUNGLE_WATER = ARFOBlocks.createFluidBlock(TraverseFluids.STILL_TRAVERSE_MINI_JUNGLE_WATER, "traverse_mini_jungle_water");

    public static final Block TRAVERSE_RED_AUTUMNAL_LEAVES_CARPET = ARFOBlocks.createBlock(new ARFOLeavesCarpetBlock(), "traverse_red_autumnal_leaves_carpet");
    public static final Block TRAVERSE_YELLOW_AUTUMNAL_LEAVES_CARPET = ARFOBlocks.createBlock(new ARFOLeavesCarpetBlock(), "traverse_yellow_autumnal_leaves_carpet");
    public static final Block TRAVERSE_ORANGE_AUTUMNAL_LEAVES_CARPET = ARFOBlocks.createBlock(new ARFOLeavesCarpetBlock(), "traverse_orange_autumnal_leaves_carpet");
    public static final Block TRAVERSE_BROWN_AUTUMNAL_LEAVES_CARPET = ARFOBlocks.createBlock(new ARFOLeavesCarpetBlock(), "traverse_brown_autumnal_leaves_carpet");

    public static final Block TRAVERSE_ARID_HIGHLANDS_GRASS_BLOCK = ARFOBlocks.createBlock(new ARFOSpreadableGrassBlock(), "traverse_arid_highlands_grass_block");
    public static final Block TRAVERSE_ARID_HIGHLANDS_GRASS_SLAB = ARFOBlocks.createBlock(new ARFOSpreadableGrassSlab(), "traverse_arid_highlands_grass_slab");
    public static final Block GLOWING_TRAVERSE_ARID_HIGHLANDS_GRASS_BLOCK = ARFOBlocks.createBlock(new ARFOGlowingGrassBlock(), "glowing_traverse_arid_highlands_grass_block");
    public static final Block TRAVERSE_ARID_HIGHLANDS_JUNGLE_LEAVES = ARFOBlocks.createBlock(new ARFOJungleLeavesBlock(), "traverse_arid_highlands_jungle_leaves");
    public static final Block TRAVERSE_ARID_HIGHLANDS_JUNGLE_LEAVES_CARPET = ARFOBlocks.createBlock(new ARFOLeavesCarpetBlock(), "traverse_arid_highlands_jungle_leaves_carpet");
    public static final Block TRAVERSE_ARID_HIGHLANDS_OAK_LEAVES = ARFOBlocks.createBlock(new ARFOOakLeavesBlock(), "traverse_arid_highlands_oak_leaves");
    public static final Block TRAVERSE_ARID_HIGHLANDS_OAK_LEAVES_CARPET = ARFOBlocks.createBlock(new ARFOLeavesCarpetBlock(), "traverse_arid_highlands_oak_leaves_carpet");
    public static final Block TRAVERSE_ARID_HIGHLANDS_DARK_OAK_LEAVES = ARFOBlocks.createBlock(new ARFODarkOakLeavesBlock(), "traverse_arid_highlands_dark_oak_leaves");
    public static final Block TRAVERSE_ARID_HIGHLANDS_DARK_OAK_LEAVES_CARPET = ARFOBlocks.createBlock(new ARFOLeavesCarpetBlock(), "traverse_arid_highlands_dark_oak_leaves_carpet");
    public static final Block TRAVERSE_ARID_HIGHLANDS_ACACIA_LEAVES = ARFOBlocks.createBlock(new ARFOAcaciaLeavesBlock(), "traverse_arid_highlands_acacia_leaves");
    public static final Block TRAVERSE_ARID_HIGHLANDS_ACACIA_LEAVES_CARPET = ARFOBlocks.createBlock(new ARFOLeavesCarpetBlock(), "traverse_arid_highlands_acacia_leaves_carpet");
    public static final Block TRAVERSE_ARID_HIGHLANDS_GRASS = ARFOBlocks.createBlock(new ARFOGrass(), "traverse_arid_highlands_grass");
    public static final Block TALL_TRAVERSE_ARID_HIGHLANDS_GRASS = ARFOBlocks.createBlock(new ARFOTallGrass(), "tall_traverse_arid_highlands_grass");
    public static final Block TRAVERSE_ARID_HIGHLANDS_FERN = ARFOBlocks.createBlock(new ARFOFernBlock(), "traverse_arid_highlands_fern");
    public static final Block LARGE_TRAVERSE_ARID_HIGHLANDS_FERN = ARFOBlocks.createBlock(new ARFOLargeFernBlock(), "large_traverse_arid_highlands_fern");
    public static final Block TRAVERSE_ARID_HIGHLANDS_SUGAR_CANE = ARFOBlocks.createBlock(new ARFOSugarCaneBlock(), "traverse_arid_highlands_sugar_cane");
    public static final Block TRAVERSE_ARID_HIGHLANDS_VINE = ARFOBlocks.createBlock(new ARFOVinesBlock(), "traverse_arid_highlands_vine");
    public static final Block POTTED_ARID_HIGHLANDS_FERN = ARFOBlocks.createPottedBlock(TRAVERSE_ARID_HIGHLANDS_FERN, "traverse_arid_highlands_fern");

    public static final Block TRAVERSE_AUTUMNAL_WOODS_GRASS_BLOCK = ARFOBlocks.createBlock(new ARFOSpreadableGrassBlock(), "traverse_autumnal_woods_grass_block");
    public static final Block TRAVERSE_AUTUMNAL_WOODS_GRASS_SLAB = ARFOBlocks.createBlock(new ARFOSpreadableGrassSlab(), "traverse_autumnal_woods_grass_slab");
    public static final Block GLOWING_TRAVERSE_AUTUMNAL_WOODS_GRASS_BLOCK = ARFOBlocks.createBlock(new ARFOGlowingGrassBlock(), "glowing_traverse_autumnal_woods_grass_block");
    public static final Block TRAVERSE_AUTUMNAL_WOODS_JUNGLE_LEAVES = ARFOBlocks.createBlock(new ARFOJungleLeavesBlock(), "traverse_autumnal_woods_jungle_leaves");
    public static final Block TRAVERSE_AUTUMNAL_WOODS_JUNGLE_LEAVES_CARPET = ARFOBlocks.createBlock(new ARFOLeavesCarpetBlock(), "traverse_autumnal_woods_jungle_leaves_carpet");
    public static final Block TRAVERSE_AUTUMNAL_WOODS_OAK_LEAVES = ARFOBlocks.createBlock(new ARFOOakLeavesBlock(), "traverse_autumnal_woods_oak_leaves");
    public static final Block TRAVERSE_AUTUMNAL_WOODS_OAK_LEAVES_CARPET = ARFOBlocks.createBlock(new ARFOLeavesCarpetBlock(), "traverse_autumnal_woods_oak_leaves_carpet");
    public static final Block TRAVERSE_AUTUMNAL_WOODS_DARK_OAK_LEAVES = ARFOBlocks.createBlock(new ARFODarkOakLeavesBlock(), "traverse_autumnal_woods_dark_oak_leaves");
    public static final Block TRAVERSE_AUTUMNAL_WOODS_DARK_OAK_LEAVES_CARPET = ARFOBlocks.createBlock(new ARFOLeavesCarpetBlock(), "traverse_autumnal_woods_dark_oak_leaves_carpet");
    public static final Block TRAVERSE_AUTUMNAL_WOODS_ACACIA_LEAVES = ARFOBlocks.createBlock(new ARFOAcaciaLeavesBlock(), "traverse_autumnal_woods_acacia_leaves");
    public static final Block TRAVERSE_AUTUMNAL_WOODS_ACACIA_LEAVES_CARPET = ARFOBlocks.createBlock(new ARFOLeavesCarpetBlock(), "traverse_autumnal_woods_acacia_leaves_carpet");
    public static final Block TRAVERSE_AUTUMNAL_WOODS_GRASS = ARFOBlocks.createBlock(new ARFOGrass(), "traverse_autumnal_woods_grass");
    public static final Block TALL_TRAVERSE_AUTUMNAL_WOODS_GRASS = ARFOBlocks.createBlock(new ARFOTallGrass(), "tall_traverse_autumnal_woods_grass");
    public static final Block TRAVERSE_AUTUMNAL_WOODS_FERN = ARFOBlocks.createBlock(new ARFOFernBlock(), "traverse_autumnal_woods_fern");
    public static final Block LARGE_TRAVERSE_AUTUMNAL_WOODS_FERN = ARFOBlocks.createBlock(new ARFOLargeFernBlock(), "large_traverse_autumnal_woods_fern");
    public static final Block TRAVERSE_AUTUMNAL_WOODS_SUGAR_CANE = ARFOBlocks.createBlock(new ARFOSugarCaneBlock(), "traverse_autumnal_woods_sugar_cane");
    public static final Block TRAVERSE_AUTUMNAL_WOODS_VINE = ARFOBlocks.createBlock(new ARFOVinesBlock(), "traverse_autumnal_woods_vine");
    public static final Block POTTED_AUTUMNAL_WOODS_FERN = ARFOBlocks.createPottedBlock(TRAVERSE_AUTUMNAL_WOODS_FERN, "traverse_autumnal_woods_fern");

    public static final Block TRAVERSE_CLIFFS_GRASS_BLOCK = ARFOBlocks.createBlock(new ARFOSpreadableGrassBlock(), "traverse_cliffs_grass_block");
    public static final Block TRAVERSE_CLIFFS_GRASS_SLAB = ARFOBlocks.createBlock(new ARFOSpreadableGrassSlab(), "traverse_cliffs_grass_slab");
    public static final Block GLOWING_TRAVERSE_CLIFFS_GRASS_BLOCK = ARFOBlocks.createBlock(new ARFOGlowingGrassBlock(), "glowing_traverse_cliffs_grass_block");
    public static final Block TRAVERSE_CLIFFS_JUNGLE_LEAVES = ARFOBlocks.createBlock(new ARFOJungleLeavesBlock(), "traverse_cliffs_jungle_leaves");
    public static final Block TRAVERSE_CLIFFS_JUNGLE_LEAVES_CARPET = ARFOBlocks.createBlock(new ARFOLeavesCarpetBlock(), "traverse_cliffs_jungle_leaves_carpet");
    public static final Block TRAVERSE_CLIFFS_OAK_LEAVES = ARFOBlocks.createBlock(new ARFOOakLeavesBlock(), "traverse_cliffs_oak_leaves");
    public static final Block TRAVERSE_CLIFFS_OAK_LEAVES_CARPET = ARFOBlocks.createBlock(new ARFOLeavesCarpetBlock(), "traverse_cliffs_oak_leaves_carpet");
    public static final Block TRAVERSE_CLIFFS_DARK_OAK_LEAVES = ARFOBlocks.createBlock(new ARFODarkOakLeavesBlock(), "traverse_cliffs_dark_oak_leaves");
    public static final Block TRAVERSE_CLIFFS_DARK_OAK_LEAVES_CARPET = ARFOBlocks.createBlock(new ARFOLeavesCarpetBlock(), "traverse_cliffs_dark_oak_leaves_carpet");
    public static final Block TRAVERSE_CLIFFS_ACACIA_LEAVES = ARFOBlocks.createBlock(new ARFOAcaciaLeavesBlock(), "traverse_cliffs_acacia_leaves");
    public static final Block TRAVERSE_CLIFFS_ACACIA_LEAVES_CARPET = ARFOBlocks.createBlock(new ARFOLeavesCarpetBlock(), "traverse_cliffs_acacia_leaves_carpet");
    public static final Block TRAVERSE_CLIFFS_GRASS = ARFOBlocks.createBlock(new ARFOGrass(), "traverse_cliffs_grass");
    public static final Block TALL_TRAVERSE_CLIFFS_GRASS = ARFOBlocks.createBlock(new ARFOTallGrass(), "tall_traverse_cliffs_grass");
    public static final Block TRAVERSE_CLIFFS_FERN = ARFOBlocks.createBlock(new ARFOFernBlock(), "traverse_cliffs_fern");
    public static final Block LARGE_TRAVERSE_CLIFFS_FERN = ARFOBlocks.createBlock(new ARFOLargeFernBlock(), "large_traverse_cliffs_fern");
    public static final Block TRAVERSE_CLIFFS_SUGAR_CANE = ARFOBlocks.createBlock(new ARFOSugarCaneBlock(), "traverse_cliffs_sugar_cane");
    public static final Block TRAVERSE_CLIFFS_VINE = ARFOBlocks.createBlock(new ARFOVinesBlock(), "traverse_cliffs_vine");
    public static final Block POTTED_CLIFFS_FERN = ARFOBlocks.createPottedBlock(TRAVERSE_CLIFFS_FERN, "traverse_cliffs_fern");

    public static final Block TRAVERSE_SNOWY_CLIFFS_GRASS_BLOCK = ARFOBlocks.createBlock(new ARFOSpreadableGrassBlock(), "traverse_snowy_cliffs_grass_block");
    public static final Block TRAVERSE_SNOWY_CLIFFS_GRASS_SLAB = ARFOBlocks.createBlock(new ARFOSpreadableGrassSlab(), "traverse_snowy_cliffs_grass_slab");
    public static final Block GLOWING_TRAVERSE_SNOWY_CLIFFS_GRASS_BLOCK = ARFOBlocks.createBlock(new ARFOGlowingGrassBlock(), "glowing_traverse_snowy_cliffs_grass_block");
    public static final Block TRAVERSE_SNOWY_CLIFFS_JUNGLE_LEAVES = ARFOBlocks.createBlock(new ARFOJungleLeavesBlock(), "traverse_snowy_cliffs_jungle_leaves");
    public static final Block TRAVERSE_SNOWY_CLIFFS_JUNGLE_LEAVES_CARPET = ARFOBlocks.createBlock(new ARFOLeavesCarpetBlock(), "traverse_snowy_cliffs_jungle_leaves_carpet");
    public static final Block TRAVERSE_SNOWY_CLIFFS_OAK_LEAVES = ARFOBlocks.createBlock(new ARFOOakLeavesBlock(), "traverse_snowy_cliffs_oak_leaves");
    public static final Block TRAVERSE_SNOWY_CLIFFS_OAK_LEAVES_CARPET = ARFOBlocks.createBlock(new ARFOLeavesCarpetBlock(), "traverse_snowy_cliffs_oak_leaves_carpet");
    public static final Block TRAVERSE_SNOWY_CLIFFS_DARK_OAK_LEAVES = ARFOBlocks.createBlock(new ARFODarkOakLeavesBlock(), "traverse_snowy_cliffs_dark_oak_leaves");
    public static final Block TRAVERSE_SNOWY_CLIFFS_DARK_OAK_LEAVES_CARPET = ARFOBlocks.createBlock(new ARFOLeavesCarpetBlock(), "traverse_snowy_cliffs_dark_oak_leaves_carpet");
    public static final Block TRAVERSE_SNOWY_CLIFFS_ACACIA_LEAVES = ARFOBlocks.createBlock(new ARFOAcaciaLeavesBlock(), "traverse_snowy_cliffs_acacia_leaves");
    public static final Block TRAVERSE_SNOWY_CLIFFS_ACACIA_LEAVES_CARPET = ARFOBlocks.createBlock(new ARFOLeavesCarpetBlock(), "traverse_snowy_cliffs_acacia_leaves_carpet");
    public static final Block TRAVERSE_SNOWY_CLIFFS_GRASS = ARFOBlocks.createBlock(new ARFOGrass(), "traverse_snowy_cliffs_grass");
    public static final Block TALL_TRAVERSE_SNOWY_CLIFFS_GRASS = ARFOBlocks.createBlock(new ARFOTallGrass(), "tall_traverse_snowy_cliffs_grass");
    public static final Block TRAVERSE_SNOWY_CLIFFS_FERN = ARFOBlocks.createBlock(new ARFOFernBlock(), "traverse_snowy_cliffs_fern");
    public static final Block LARGE_TRAVERSE_SNOWY_CLIFFS_FERN = ARFOBlocks.createBlock(new ARFOLargeFernBlock(), "large_traverse_snowy_cliffs_fern");
    public static final Block TRAVERSE_SNOWY_CLIFFS_SUGAR_CANE = ARFOBlocks.createBlock(new ARFOSugarCaneBlock(), "traverse_snowy_cliffs_sugar_cane");
    public static final Block TRAVERSE_SNOWY_CLIFFS_VINE = ARFOBlocks.createBlock(new ARFOVinesBlock(), "traverse_snowy_cliffs_vine");
    public static final Block POTTED_SNOWY_CLIFFS_FERN = ARFOBlocks.createPottedBlock(TRAVERSE_SNOWY_CLIFFS_FERN, "traverse_snowy_cliffs_fern");

    public static final Block TRAVERSE_CONIFEROUS_FOREST_GRASS_BLOCK = ARFOBlocks.createBlock(new ARFOSpreadableGrassBlock(), "traverse_coniferous_forest_grass_block");
    public static final Block TRAVERSE_CONIFEROUS_FOREST_GRASS_SLAB = ARFOBlocks.createBlock(new ARFOSpreadableGrassSlab(), "traverse_coniferous_forest_grass_slab");
    public static final Block GLOWING_TRAVERSE_CONIFEROUS_FOREST_GRASS_BLOCK = ARFOBlocks.createBlock(new ARFOGlowingGrassBlock(), "glowing_traverse_coniferous_forest_grass_block");
    public static final Block TRAVERSE_CONIFEROUS_FOREST_JUNGLE_LEAVES = ARFOBlocks.createBlock(new ARFOJungleLeavesBlock(), "traverse_coniferous_forest_jungle_leaves");
    public static final Block TRAVERSE_CONIFEROUS_FOREST_JUNGLE_LEAVES_CARPET = ARFOBlocks.createBlock(new ARFOLeavesCarpetBlock(), "traverse_coniferous_forest_jungle_leaves_carpet");
    public static final Block TRAVERSE_CONIFEROUS_FOREST_OAK_LEAVES = ARFOBlocks.createBlock(new ARFOOakLeavesBlock(), "traverse_coniferous_forest_oak_leaves");
    public static final Block TRAVERSE_CONIFEROUS_FOREST_OAK_LEAVES_CARPET = ARFOBlocks.createBlock(new ARFOLeavesCarpetBlock(), "traverse_coniferous_forest_oak_leaves_carpet");
    public static final Block TRAVERSE_CONIFEROUS_FOREST_DARK_OAK_LEAVES = ARFOBlocks.createBlock(new ARFODarkOakLeavesBlock(), "traverse_coniferous_forest_dark_oak_leaves");
    public static final Block TRAVERSE_CONIFEROUS_FOREST_DARK_OAK_LEAVES_CARPET = ARFOBlocks.createBlock(new ARFOLeavesCarpetBlock(), "traverse_coniferous_forest_dark_oak_leaves_carpet");
    public static final Block TRAVERSE_CONIFEROUS_FOREST_ACACIA_LEAVES = ARFOBlocks.createBlock(new ARFOAcaciaLeavesBlock(), "traverse_coniferous_forest_acacia_leaves");
    public static final Block TRAVERSE_CONIFEROUS_FOREST_ACACIA_LEAVES_CARPET = ARFOBlocks.createBlock(new ARFOLeavesCarpetBlock(), "traverse_coniferous_forest_acacia_leaves_carpet");
    public static final Block TRAVERSE_CONIFEROUS_FOREST_GRASS = ARFOBlocks.createBlock(new ARFOGrass(), "traverse_coniferous_forest_grass");
    public static final Block TALL_TRAVERSE_CONIFEROUS_FOREST_GRASS = ARFOBlocks.createBlock(new ARFOTallGrass(), "tall_traverse_coniferous_forest_grass");
    public static final Block TRAVERSE_CONIFEROUS_FOREST_FERN = ARFOBlocks.createBlock(new ARFOFernBlock(), "traverse_coniferous_forest_fern");
    public static final Block LARGE_TRAVERSE_CONIFEROUS_FOREST_FERN = ARFOBlocks.createBlock(new ARFOLargeFernBlock(), "large_traverse_coniferous_forest_fern");
    public static final Block TRAVERSE_CONIFEROUS_FOREST_SUGAR_CANE = ARFOBlocks.createBlock(new ARFOSugarCaneBlock(), "traverse_coniferous_forest_sugar_cane");
    public static final Block TRAVERSE_CONIFEROUS_FOREST_VINE = ARFOBlocks.createBlock(new ARFOVinesBlock(), "traverse_coniferous_forest_vine");
    public static final Block POTTED_CONIFEROUS_FOREST_FERN = ARFOBlocks.createPottedBlock(TRAVERSE_CONIFEROUS_FOREST_FERN, "traverse_coniferous_forest_fern");

    public static final Block TRAVERSE_SNOWY_CONIFEROUS_FOREST_GRASS_BLOCK = ARFOBlocks.createBlock(new ARFOSpreadableGrassBlock(), "traverse_snowy_coniferous_forest_grass_block");
    public static final Block TRAVERSE_SNOWY_CONIFEROUS_FOREST_GRASS_SLAB = ARFOBlocks.createBlock(new ARFOSpreadableGrassSlab(), "traverse_snowy_coniferous_forest_grass_slab");
    public static final Block GLOWING_TRAVERSE_SNOWY_CONIFEROUS_FOREST_GRASS_BLOCK = ARFOBlocks.createBlock(new ARFOGlowingGrassBlock(), "glowing_traverse_snowy_coniferous_forest_grass_block");
    public static final Block TRAVERSE_SNOWY_CONIFEROUS_FOREST_JUNGLE_LEAVES = ARFOBlocks.createBlock(new ARFOJungleLeavesBlock(), "traverse_snowy_coniferous_forest_jungle_leaves");
    public static final Block TRAVERSE_SNOWY_CONIFEROUS_FOREST_JUNGLE_LEAVES_CARPET = ARFOBlocks.createBlock(new ARFOLeavesCarpetBlock(), "traverse_snowy_coniferous_forest_jungle_leaves_carpet");
    public static final Block TRAVERSE_SNOWY_CONIFEROUS_FOREST_OAK_LEAVES = ARFOBlocks.createBlock(new ARFOOakLeavesBlock(), "traverse_snowy_coniferous_forest_oak_leaves");
    public static final Block TRAVERSE_SNOWY_CONIFEROUS_FOREST_OAK_LEAVES_CARPET = ARFOBlocks.createBlock(new ARFOLeavesCarpetBlock(), "traverse_snowy_coniferous_forest_oak_leaves_carpet");
    public static final Block TRAVERSE_SNOWY_CONIFEROUS_FOREST_DARK_OAK_LEAVES = ARFOBlocks.createBlock(new ARFODarkOakLeavesBlock(), "traverse_snowy_coniferous_forest_dark_oak_leaves");
    public static final Block TRAVERSE_SNOWY_CONIFEROUS_FOREST_DARK_OAK_LEAVES_CARPET = ARFOBlocks.createBlock(new ARFOLeavesCarpetBlock(), "traverse_snowy_coniferous_forest_dark_oak_leaves_carpet");
    public static final Block TRAVERSE_SNOWY_CONIFEROUS_FOREST_ACACIA_LEAVES = ARFOBlocks.createBlock(new ARFOAcaciaLeavesBlock(), "traverse_snowy_coniferous_forest_acacia_leaves");
    public static final Block TRAVERSE_SNOWY_CONIFEROUS_FOREST_ACACIA_LEAVES_CARPET = ARFOBlocks.createBlock(new ARFOLeavesCarpetBlock(), "traverse_snowy_coniferous_forest_acacia_leaves_carpet");
    public static final Block TRAVERSE_SNOWY_CONIFEROUS_FOREST_GRASS = ARFOBlocks.createBlock(new ARFOGrass(), "traverse_snowy_coniferous_forest_grass");
    public static final Block TALL_TRAVERSE_SNOWY_CONIFEROUS_FOREST_GRASS = ARFOBlocks.createBlock(new ARFOTallGrass(), "tall_traverse_snowy_coniferous_forest_grass");
    public static final Block TRAVERSE_SNOWY_CONIFEROUS_FOREST_FERN = ARFOBlocks.createBlock(new ARFOFernBlock(), "traverse_snowy_coniferous_forest_fern");
    public static final Block LARGE_TRAVERSE_SNOWY_CONIFEROUS_FOREST_FERN = ARFOBlocks.createBlock(new ARFOLargeFernBlock(), "large_traverse_snowy_coniferous_forest_fern");
    public static final Block TRAVERSE_SNOWY_CONIFEROUS_FOREST_SUGAR_CANE = ARFOBlocks.createBlock(new ARFOSugarCaneBlock(), "traverse_snowy_coniferous_forest_sugar_cane");
    public static final Block TRAVERSE_SNOWY_CONIFEROUS_FOREST_VINE = ARFOBlocks.createBlock(new ARFOVinesBlock(), "traverse_snowy_coniferous_forest_vine");
    public static final Block POTTED_SNOWY_CONIFEROUS_FOREST_FERN = ARFOBlocks.createPottedBlock(TRAVERSE_SNOWY_CONIFEROUS_FOREST_FERN, "traverse_snowy_coniferous_forest_fern");

    public static final Block TRAVERSE_MEADOW_GRASS_BLOCK = ARFOBlocks.createBlock(new ARFOSpreadableGrassBlock(), "traverse_meadow_grass_block");
    public static final Block TRAVERSE_MEADOW_GRASS_SLAB = ARFOBlocks.createBlock(new ARFOSpreadableGrassSlab(), "traverse_meadow_grass_slab");
    public static final Block GLOWING_TRAVERSE_MEADOW_GRASS_BLOCK = ARFOBlocks.createBlock(new ARFOGlowingGrassBlock(), "glowing_traverse_meadow_grass_block");
    public static final Block TRAVERSE_MEADOW_JUNGLE_LEAVES = ARFOBlocks.createBlock(new ARFOJungleLeavesBlock(), "traverse_meadow_jungle_leaves");
    public static final Block TRAVERSE_MEADOW_JUNGLE_LEAVES_CARPET = ARFOBlocks.createBlock(new ARFOLeavesCarpetBlock(), "traverse_meadow_jungle_leaves_carpet");
    public static final Block TRAVERSE_MEADOW_OAK_LEAVES = ARFOBlocks.createBlock(new ARFOOakLeavesBlock(), "traverse_meadow_oak_leaves");
    public static final Block TRAVERSE_MEADOW_OAK_LEAVES_CARPET = ARFOBlocks.createBlock(new ARFOLeavesCarpetBlock(), "traverse_meadow_oak_leaves_carpet");
    public static final Block TRAVERSE_MEADOW_DARK_OAK_LEAVES = ARFOBlocks.createBlock(new ARFODarkOakLeavesBlock(), "traverse_meadow_dark_oak_leaves");
    public static final Block TRAVERSE_MEADOW_DARK_OAK_LEAVES_CARPET = ARFOBlocks.createBlock(new ARFOLeavesCarpetBlock(), "traverse_meadow_dark_oak_leaves_carpet");
    public static final Block TRAVERSE_MEADOW_ACACIA_LEAVES = ARFOBlocks.createBlock(new ARFOAcaciaLeavesBlock(), "traverse_meadow_acacia_leaves");
    public static final Block TRAVERSE_MEADOW_ACACIA_LEAVES_CARPET = ARFOBlocks.createBlock(new ARFOLeavesCarpetBlock(), "traverse_meadow_acacia_leaves_carpet");
    public static final Block TRAVERSE_MEADOW_GRASS = ARFOBlocks.createBlock(new ARFOGrass(), "traverse_meadow_grass");
    public static final Block TALL_TRAVERSE_MEADOW_GRASS = ARFOBlocks.createBlock(new ARFOTallGrass(), "tall_traverse_meadow_grass");
    public static final Block TRAVERSE_MEADOW_FERN = ARFOBlocks.createBlock(new ARFOFernBlock(), "traverse_meadow_fern");
    public static final Block LARGE_TRAVERSE_MEADOW_FERN = ARFOBlocks.createBlock(new ARFOLargeFernBlock(), "large_traverse_meadow_fern");
    public static final Block TRAVERSE_MEADOW_SUGAR_CANE = ARFOBlocks.createBlock(new ARFOSugarCaneBlock(), "traverse_meadow_sugar_cane");
    public static final Block TRAVERSE_MEADOW_VINE = ARFOBlocks.createBlock(new ARFOVinesBlock(), "traverse_meadow_vine");
    public static final Block POTTED_MEADOW_FERN = ARFOBlocks.createPottedBlock(TRAVERSE_MEADOW_FERN, "traverse_meadow_fern");

    public static final Block TRAVERSE_LUSH_SWAMP_GRASS_BLOCK = ARFOBlocks.createBlock(new ARFOSpreadableGrassBlock(), "traverse_lush_swamp_grass_block");
    public static final Block TRAVERSE_LUSH_SWAMP_GRASS_SLAB = ARFOBlocks.createBlock(new ARFOSpreadableGrassSlab(), "traverse_lush_swamp_grass_slab");
    public static final Block GLOWING_TRAVERSE_LUSH_SWAMP_GRASS_BLOCK = ARFOBlocks.createBlock(new ARFOGlowingGrassBlock(), "glowing_traverse_lush_swamp_grass_block");
    public static final Block TRAVERSE_LUSH_SWAMP_JUNGLE_LEAVES = ARFOBlocks.createBlock(new ARFOJungleLeavesBlock(), "traverse_lush_swamp_jungle_leaves");
    public static final Block TRAVERSE_LUSH_SWAMP_JUNGLE_LEAVES_CARPET = ARFOBlocks.createBlock(new ARFOLeavesCarpetBlock(), "traverse_lush_swamp_jungle_leaves_carpet");
    public static final Block TRAVERSE_LUSH_SWAMP_OAK_LEAVES = ARFOBlocks.createBlock(new ARFOOakLeavesBlock(), "traverse_lush_swamp_oak_leaves");
    public static final Block TRAVERSE_LUSH_SWAMP_OAK_LEAVES_CARPET = ARFOBlocks.createBlock(new ARFOLeavesCarpetBlock(), "traverse_lush_swamp_oak_leaves_carpet");
    public static final Block TRAVERSE_LUSH_SWAMP_DARK_OAK_LEAVES = ARFOBlocks.createBlock(new ARFODarkOakLeavesBlock(), "traverse_lush_swamp_dark_oak_leaves");
    public static final Block TRAVERSE_LUSH_SWAMP_DARK_OAK_LEAVES_CARPET = ARFOBlocks.createBlock(new ARFOLeavesCarpetBlock(), "traverse_lush_swamp_dark_oak_leaves_carpet");
    public static final Block TRAVERSE_LUSH_SWAMP_ACACIA_LEAVES = ARFOBlocks.createBlock(new ARFOAcaciaLeavesBlock(), "traverse_lush_swamp_acacia_leaves");
    public static final Block TRAVERSE_LUSH_SWAMP_ACACIA_LEAVES_CARPET = ARFOBlocks.createBlock(new ARFOLeavesCarpetBlock(), "traverse_lush_swamp_acacia_leaves_carpet");
    public static final Block TRAVERSE_LUSH_SWAMP_GRASS = ARFOBlocks.createBlock(new ARFOGrass(), "traverse_lush_swamp_grass");
    public static final Block TALL_TRAVERSE_LUSH_SWAMP_GRASS = ARFOBlocks.createBlock(new ARFOTallGrass(), "tall_traverse_lush_swamp_grass");
    public static final Block TRAVERSE_LUSH_SWAMP_FERN = ARFOBlocks.createBlock(new ARFOFernBlock(), "traverse_lush_swamp_fern");
    public static final Block LARGE_TRAVERSE_LUSH_SWAMP_FERN = ARFOBlocks.createBlock(new ARFOLargeFernBlock(), "large_traverse_lush_swamp_fern");
    public static final Block TRAVERSE_LUSH_SWAMP_SUGAR_CANE = ARFOBlocks.createBlock(new ARFOSugarCaneBlock(), "traverse_lush_swamp_sugar_cane");
    public static final Block TRAVERSE_LUSH_SWAMP_VINE = ARFOBlocks.createBlock(new ARFOVinesBlock(), "traverse_lush_swamp_vine");
    public static final Block POTTED_TRAVERSE_LUSH_SWAMP_FERN = ARFOBlocks.createPottedBlock(TRAVERSE_LUSH_SWAMP_FERN, "traverse_lush_swamp_fern");

    public static final Block TRAVERSE_PLAINS_PLATEAU_GRASS_BLOCK = ARFOBlocks.createBlock(new ARFOSpreadableGrassBlock(), "traverse_plains_plateau_grass_block");
    public static final Block TRAVERSE_PLAINS_PLATEAU_GRASS_SLAB = ARFOBlocks.createBlock(new ARFOSpreadableGrassSlab(), "traverse_plains_plateau_grass_slab");
    public static final Block GLOWING_TRAVERSE_PLAINS_PLATEAU_GRASS_BLOCK = ARFOBlocks.createBlock(new ARFOGlowingGrassBlock(), "glowing_traverse_plains_plateau_grass_block");
    public static final Block TRAVERSE_PLAINS_PLATEAU_JUNGLE_LEAVES = ARFOBlocks.createBlock(new ARFOJungleLeavesBlock(), "traverse_plains_plateau_jungle_leaves");
    public static final Block TRAVERSE_PLAINS_PLATEAU_JUNGLE_LEAVES_CARPET = ARFOBlocks.createBlock(new ARFOLeavesCarpetBlock(), "traverse_plains_plateau_jungle_leaves_carpet");
    public static final Block TRAVERSE_PLAINS_PLATEAU_OAK_LEAVES = ARFOBlocks.createBlock(new ARFOOakLeavesBlock(), "traverse_plains_plateau_oak_leaves");
    public static final Block TRAVERSE_PLAINS_PLATEAU_OAK_LEAVES_CARPET = ARFOBlocks.createBlock(new ARFOLeavesCarpetBlock(), "traverse_plains_plateau_oak_leaves_carpet");
    public static final Block TRAVERSE_PLAINS_PLATEAU_DARK_OAK_LEAVES = ARFOBlocks.createBlock(new ARFODarkOakLeavesBlock(), "traverse_plains_plateau_dark_oak_leaves");
    public static final Block TRAVERSE_PLAINS_PLATEAU_DARK_OAK_LEAVES_CARPET = ARFOBlocks.createBlock(new ARFOLeavesCarpetBlock(), "traverse_plains_plateau_dark_oak_leaves_carpet");
    public static final Block TRAVERSE_PLAINS_PLATEAU_ACACIA_LEAVES = ARFOBlocks.createBlock(new ARFOAcaciaLeavesBlock(), "traverse_plains_plateau_acacia_leaves");
    public static final Block TRAVERSE_PLAINS_PLATEAU_ACACIA_LEAVES_CARPET = ARFOBlocks.createBlock(new ARFOLeavesCarpetBlock(), "traverse_plains_plateau_acacia_leaves_carpet");
    public static final Block TRAVERSE_PLAINS_PLATEAU_GRASS = ARFOBlocks.createBlock(new ARFOGrass(), "traverse_plains_plateau_grass");
    public static final Block TALL_TRAVERSE_PLAINS_PLATEAU_GRASS = ARFOBlocks.createBlock(new ARFOTallGrass(), "tall_traverse_plains_plateau_grass");
    public static final Block TRAVERSE_PLAINS_PLATEAU_FERN = ARFOBlocks.createBlock(new ARFOFernBlock(), "traverse_plains_plateau_fern");
    public static final Block LARGE_TRAVERSE_PLAINS_PLATEAU_FERN = ARFOBlocks.createBlock(new ARFOLargeFernBlock(), "large_traverse_plains_plateau_fern");
    public static final Block TRAVERSE_PLAINS_PLATEAU_SUGAR_CANE = ARFOBlocks.createBlock(new ARFOSugarCaneBlock(), "traverse_plains_plateau_sugar_cane");
    public static final Block TRAVERSE_PLAINS_PLATEAU_VINE = ARFOBlocks.createBlock(new ARFOVinesBlock(), "traverse_plains_plateau_vine");
    public static final Block POTTED_PLAINS_PLATEAU_FERN = ARFOBlocks.createPottedBlock(TRAVERSE_PLAINS_PLATEAU_FERN, "traverse_plains_plateau_fern");

    public static final Block TRAVERSE_ROLLING_HILLS_GRASS_BLOCK = ARFOBlocks.createBlock(new ARFOSpreadableGrassBlock(), "traverse_rolling_hills_grass_block");
    public static final Block TRAVERSE_ROLLING_HILLS_GRASS_SLAB = ARFOBlocks.createBlock(new ARFOSpreadableGrassSlab(), "traverse_rolling_hills_grass_slab");
    public static final Block GLOWING_TRAVERSE_ROLLING_HILLS_GRASS_BLOCK = ARFOBlocks.createBlock(new ARFOGlowingGrassBlock(), "glowing_traverse_rolling_hills_grass_block");
    public static final Block TRAVERSE_ROLLING_HILLS_JUNGLE_LEAVES = ARFOBlocks.createBlock(new ARFOJungleLeavesBlock(), "traverse_rolling_hills_jungle_leaves");
    public static final Block TRAVERSE_ROLLING_HILLS_JUNGLE_LEAVES_CARPET = ARFOBlocks.createBlock(new ARFOLeavesCarpetBlock(), "traverse_rolling_hills_jungle_leaves_carpet");
    public static final Block TRAVERSE_ROLLING_HILLS_OAK_LEAVES = ARFOBlocks.createBlock(new ARFOOakLeavesBlock(), "traverse_rolling_hills_oak_leaves");
    public static final Block TRAVERSE_ROLLING_HILLS_OAK_LEAVES_CARPET = ARFOBlocks.createBlock(new ARFOLeavesCarpetBlock(), "traverse_rolling_hills_oak_leaves_carpet");
    public static final Block TRAVERSE_ROLLING_HILLS_DARK_OAK_LEAVES = ARFOBlocks.createBlock(new ARFODarkOakLeavesBlock(), "traverse_rolling_hills_dark_oak_leaves");
    public static final Block TRAVERSE_ROLLING_HILLS_DARK_OAK_LEAVES_CARPET = ARFOBlocks.createBlock(new ARFOLeavesCarpetBlock(), "traverse_rolling_hills_dark_oak_leaves_carpet");
    public static final Block TRAVERSE_ROLLING_HILLS_ACACIA_LEAVES = ARFOBlocks.createBlock(new ARFOAcaciaLeavesBlock(), "traverse_rolling_hills_acacia_leaves");
    public static final Block TRAVERSE_ROLLING_HILLS_ACACIA_LEAVES_CARPET = ARFOBlocks.createBlock(new ARFOLeavesCarpetBlock(), "traverse_rolling_hills_acacia_leaves_carpet");
    public static final Block TRAVERSE_ROLLING_HILLS_GRASS = ARFOBlocks.createBlock(new ARFOGrass(), "traverse_rolling_hills_grass");
    public static final Block TALL_TRAVERSE_ROLLING_HILLS_GRASS = ARFOBlocks.createBlock(new ARFOTallGrass(), "tall_traverse_rolling_hills_grass");
    public static final Block TRAVERSE_ROLLING_HILLS_FERN = ARFOBlocks.createBlock(new ARFOFernBlock(), "traverse_rolling_hills_fern");
    public static final Block LARGE_TRAVERSE_ROLLING_HILLS_FERN = ARFOBlocks.createBlock(new ARFOLargeFernBlock(), "large_traverse_rolling_hills_fern");
    public static final Block TRAVERSE_ROLLING_HILLS_SUGAR_CANE = ARFOBlocks.createBlock(new ARFOSugarCaneBlock(), "traverse_rolling_hills_sugar_cane");
    public static final Block TRAVERSE_ROLLING_HILLS_VINE = ARFOBlocks.createBlock(new ARFOVinesBlock(), "traverse_rolling_hills_vine");
    public static final Block POTTED_ROLLING_HILLS_FERN = ARFOBlocks.createPottedBlock(TRAVERSE_ROLLING_HILLS_FERN, "traverse_rolling_hills_fern");

    public static final Block TRAVERSE_WOODED_ISLAND_GRASS_BLOCK = ARFOBlocks.createBlock(new ARFOSpreadableGrassBlock(), "traverse_wooded_island_grass_block");
    public static final Block TRAVERSE_WOODED_ISLAND_GRASS_SLAB = ARFOBlocks.createBlock(new ARFOSpreadableGrassSlab(), "traverse_wooded_island_grass_slab");
    public static final Block GLOWING_TRAVERSE_WOODED_ISLAND_GRASS_BLOCK = ARFOBlocks.createBlock(new ARFOGlowingGrassBlock(), "glowing_traverse_wooded_island_grass_block");
    public static final Block TRAVERSE_WOODED_ISLAND_JUNGLE_LEAVES = ARFOBlocks.createBlock(new ARFOJungleLeavesBlock(), "traverse_wooded_island_jungle_leaves");
    public static final Block TRAVERSE_WOODED_ISLAND_JUNGLE_LEAVES_CARPET = ARFOBlocks.createBlock(new ARFOLeavesCarpetBlock(), "traverse_wooded_island_jungle_leaves_carpet");
    public static final Block TRAVERSE_WOODED_ISLAND_OAK_LEAVES = ARFOBlocks.createBlock(new ARFOOakLeavesBlock(), "traverse_wooded_island_oak_leaves");
    public static final Block TRAVERSE_WOODED_ISLAND_OAK_LEAVES_CARPET = ARFOBlocks.createBlock(new ARFOLeavesCarpetBlock(), "traverse_wooded_island_oak_leaves_carpet");
    public static final Block TRAVERSE_WOODED_ISLAND_DARK_OAK_LEAVES = ARFOBlocks.createBlock(new ARFODarkOakLeavesBlock(), "traverse_wooded_island_dark_oak_leaves");
    public static final Block TRAVERSE_WOODED_ISLAND_DARK_OAK_LEAVES_CARPET = ARFOBlocks.createBlock(new ARFOLeavesCarpetBlock(), "traverse_wooded_island_dark_oak_leaves_carpet");
    public static final Block TRAVERSE_WOODED_ISLAND_ACACIA_LEAVES = ARFOBlocks.createBlock(new ARFOAcaciaLeavesBlock(), "traverse_wooded_island_acacia_leaves");
    public static final Block TRAVERSE_WOODED_ISLAND_ACACIA_LEAVES_CARPET = ARFOBlocks.createBlock(new ARFOLeavesCarpetBlock(), "traverse_wooded_island_acacia_leaves_carpet");
    public static final Block TRAVERSE_WOODED_ISLAND_GRASS = ARFOBlocks.createBlock(new ARFOGrass(), "traverse_wooded_island_grass");
    public static final Block TALL_TRAVERSE_WOODED_ISLAND_GRASS = ARFOBlocks.createBlock(new ARFOTallGrass(), "tall_traverse_wooded_island_grass");
    public static final Block TRAVERSE_WOODED_ISLAND_FERN = ARFOBlocks.createBlock(new ARFOFernBlock(), "traverse_wooded_island_fern");
    public static final Block LARGE_TRAVERSE_WOODED_ISLAND_FERN = ARFOBlocks.createBlock(new ARFOLargeFernBlock(), "large_traverse_wooded_island_fern");
    public static final Block TRAVERSE_WOODED_ISLAND_SUGAR_CANE = ARFOBlocks.createBlock(new ARFOSugarCaneBlock(), "traverse_wooded_island_sugar_cane");
    public static final Block TRAVERSE_WOODED_ISLAND_VINE = ARFOBlocks.createBlock(new ARFOVinesBlock(), "traverse_wooded_island_vine");
    public static final Block POTTED_WOODED_ISLAND_FERN = ARFOBlocks.createPottedBlock(TRAVERSE_WOODED_ISLAND_FERN, "traverse_wooded_island_fern");

    public static final Block TRAVERSE_WOODLANDS_GRASS_BLOCK = ARFOBlocks.createBlock(new ARFOSpreadableGrassBlock(), "traverse_woodlands_grass_block");
    public static final Block TRAVERSE_WOODLANDS_GRASS_SLAB = ARFOBlocks.createBlock(new ARFOSpreadableGrassSlab(), "traverse_woodlands_grass_slab");
    public static final Block GLOWING_TRAVERSE_WOODLANDS_GRASS_BLOCK = ARFOBlocks.createBlock(new ARFOGlowingGrassBlock(), "glowing_traverse_woodlands_grass_block");
    public static final Block TRAVERSE_WOODLANDS_JUNGLE_LEAVES = ARFOBlocks.createBlock(new ARFOJungleLeavesBlock(), "traverse_woodlands_jungle_leaves");
    public static final Block TRAVERSE_WOODLANDS_JUNGLE_LEAVES_CARPET = ARFOBlocks.createBlock(new ARFOLeavesCarpetBlock(), "traverse_woodlands_jungle_leaves_carpet");
    public static final Block TRAVERSE_WOODLANDS_OAK_LEAVES = ARFOBlocks.createBlock(new ARFOOakLeavesBlock(), "traverse_woodlands_oak_leaves");
    public static final Block TRAVERSE_WOODLANDS_OAK_LEAVES_CARPET = ARFOBlocks.createBlock(new ARFOLeavesCarpetBlock(), "traverse_woodlands_oak_leaves_carpet");
    public static final Block TRAVERSE_WOODLANDS_DARK_OAK_LEAVES = ARFOBlocks.createBlock(new ARFODarkOakLeavesBlock(), "traverse_woodlands_dark_oak_leaves");
    public static final Block TRAVERSE_WOODLANDS_DARK_OAK_LEAVES_CARPET = ARFOBlocks.createBlock(new ARFOLeavesCarpetBlock(), "traverse_woodlands_dark_oak_leaves_carpet");
    public static final Block TRAVERSE_WOODLANDS_ACACIA_LEAVES = ARFOBlocks.createBlock(new ARFOAcaciaLeavesBlock(), "traverse_woodlands_acacia_leaves");
    public static final Block TRAVERSE_WOODLANDS_ACACIA_LEAVES_CARPET = ARFOBlocks.createBlock(new ARFOLeavesCarpetBlock(), "traverse_woodlands_acacia_leaves_carpet");
    public static final Block TRAVERSE_WOODLANDS_GRASS = ARFOBlocks.createBlock(new ARFOGrass(), "traverse_woodlands_grass");
    public static final Block TALL_TRAVERSE_WOODLANDS_GRASS = ARFOBlocks.createBlock(new ARFOTallGrass(), "tall_traverse_woodlands_grass");
    public static final Block TRAVERSE_WOODLANDS_FERN = ARFOBlocks.createBlock(new ARFOFernBlock(), "traverse_woodlands_fern");
    public static final Block LARGE_TRAVERSE_WOODLANDS_FERN = ARFOBlocks.createBlock(new ARFOLargeFernBlock(), "large_traverse_woodlands_fern");
    public static final Block TRAVERSE_WOODLANDS_SUGAR_CANE = ARFOBlocks.createBlock(new ARFOSugarCaneBlock(), "traverse_woodlands_sugar_cane");
    public static final Block TRAVERSE_WOODLANDS_VINE = ARFOBlocks.createBlock(new ARFOVinesBlock(), "traverse_woodlands_vine");
    public static final Block POTTED_WOODLANDS_FERN = ARFOBlocks.createPottedBlock(TRAVERSE_WOODLANDS_FERN, "traverse_woodlands_fern");

    public static final Block TRAVERSE_ARID_HIGHLANDS_OVERGROWN_STONE = ARFOBlocks.createBlock(new ARFOSpreadableStoneBlock(), "traverse_arid_highlands_overgrown_stone");
    public static final Block TRAVERSE_AUTUMNAL_WOODS_OVERGROWN_STONE = ARFOBlocks.createBlock(new ARFOSpreadableStoneBlock(), "traverse_autumnal_woods_overgrown_stone");
    public static final Block TRAVERSE_CLIFFS_OVERGROWN_STONE = ARFOBlocks.createBlock(new ARFOSpreadableStoneBlock(), "traverse_cliffs_overgrown_stone");
    public static final Block TRAVERSE_SNOWY_CLIFFS_OVERGROWN_STONE = ARFOBlocks.createBlock(new ARFOSpreadableStoneBlock(), "traverse_snowy_cliffs_overgrown_stone");
    public static final Block TRAVERSE_CONIFEROUS_FOREST_OVERGROWN_STONE = ARFOBlocks.createBlock(new ARFOSpreadableStoneBlock(), "traverse_coniferous_forest_overgrown_stone");
    public static final Block TRAVERSE_SNOWY_CONIFEROUS_FOREST_OVERGROWN_STONE = ARFOBlocks.createBlock(new ARFOSpreadableStoneBlock(), "traverse_snowy_coniferous_forest_overgrown_stone");
    public static final Block TRAVERSE_LUSH_SWAMP_OVERGROWN_STONE = ARFOBlocks.createBlock(new ARFOSpreadableStoneBlock(), "traverse_lush_swamp_overgrown_stone");
    public static final Block TRAVERSE_PLAINS_PLATEAU_OVERGROWN_STONE = ARFOBlocks.createBlock(new ARFOSpreadableStoneBlock(), "traverse_plains_plateau_overgrown_stone");
    public static final Block TRAVERSE_ROLLING_HILLS_OVERGROWN_STONE = ARFOBlocks.createBlock(new ARFOSpreadableStoneBlock(), "traverse_rolling_hills_overgrown_stone");
    public static final Block TRAVERSE_MEADOW_OVERGROWN_STONE = ARFOBlocks.createBlock(new ARFOSpreadableStoneBlock(), "traverse_meadow_overgrown_stone");
    public static final Block TRAVERSE_WOODED_ISLAND_OVERGROWN_STONE = ARFOBlocks.createBlock(new ARFOSpreadableStoneBlock(), "traverse_wooded_island_overgrown_stone");
    public static final Block TRAVERSE_WOODLANDS_OVERGROWN_STONE = ARFOBlocks.createBlock(new ARFOSpreadableStoneBlock(), "traverse_woodlands_overgrown_stone");

    public static final Block TRAVERSE_ARID_HIGHLANDS_OVERGROWN_STONE_SLAB = ARFOBlocks.createBlock(new ARFOSpreadableStoneSlab(), "traverse_arid_highlands_overgrown_stone_slab");
    public static final Block TRAVERSE_AUTUMNAL_WOODS_OVERGROWN_STONE_SLAB = ARFOBlocks.createBlock(new ARFOSpreadableStoneSlab(), "traverse_autumnal_woods_overgrown_stone_slab");
    public static final Block TRAVERSE_CLIFFS_OVERGROWN_STONE_SLAB = ARFOBlocks.createBlock(new ARFOSpreadableStoneSlab(), "traverse_cliffs_overgrown_stone_slab");
    public static final Block TRAVERSE_SNOWY_CLIFFS_OVERGROWN_STONE_SLAB = ARFOBlocks.createBlock(new ARFOSpreadableStoneSlab(), "traverse_snowy_cliffs_overgrown_stone_slab");
    public static final Block TRAVERSE_CONIFEROUS_FOREST_OVERGROWN_STONE_SLAB = ARFOBlocks.createBlock(new ARFOSpreadableStoneSlab(), "traverse_coniferous_forest_overgrown_stone_slab");
    public static final Block TRAVERSE_SNOWY_CONIFEROUS_FOREST_OVERGROWN_STONE_SLAB = ARFOBlocks.createBlock(new ARFOSpreadableStoneSlab(), "traverse_snowy_coniferous_forest_overgrown_stone_slab");
    public static final Block TRAVERSE_LUSH_SWAMP_OVERGROWN_STONE_SLAB = ARFOBlocks.createBlock(new ARFOSpreadableStoneSlab(), "traverse_lush_swamp_overgrown_stone_slab");
    public static final Block TRAVERSE_PLAINS_PLATEAU_OVERGROWN_STONE_SLAB = ARFOBlocks.createBlock(new ARFOSpreadableStoneSlab(), "traverse_plains_plateau_overgrown_stone_slab");
    public static final Block TRAVERSE_ROLLING_HILLS_OVERGROWN_STONE_SLAB = ARFOBlocks.createBlock(new ARFOSpreadableStoneSlab(), "traverse_rolling_hills_overgrown_stone_slab");
    public static final Block TRAVERSE_MEADOW_OVERGROWN_STONE_SLAB = ARFOBlocks.createBlock(new ARFOSpreadableStoneSlab(), "traverse_meadow_overgrown_stone_slab");
    public static final Block TRAVERSE_WOODED_ISLAND_OVERGROWN_STONE_SLAB = ARFOBlocks.createBlock(new ARFOSpreadableStoneSlab(), "traverse_wooded_island_overgrown_stone_slab");
    public static final Block TRAVERSE_WOODLANDS_OVERGROWN_STONE_SLAB = ARFOBlocks.createBlock(new ARFOSpreadableStoneSlab(), "traverse_woodlands_overgrown_stone_slab");

    public static final Block TRAVERSE_ARID_HIGHLANDS_OVERGROWN_NETHERRACK = ARFOBlocks.createBlock(new ARFOSpreadableNetherrackBlock(), "traverse_arid_highlands_overgrown_netherrack");
    public static final Block TRAVERSE_AUTUMNAL_WOODS_OVERGROWN_NETHERRACK = ARFOBlocks.createBlock(new ARFOSpreadableNetherrackBlock(), "traverse_autumnal_woods_overgrown_netherrack");
    public static final Block TRAVERSE_CLIFFS_OVERGROWN_NETHERRACK = ARFOBlocks.createBlock(new ARFOSpreadableNetherrackBlock(), "traverse_cliffs_overgrown_netherrack");
    public static final Block TRAVERSE_SNOWY_CLIFFS_OVERGROWN_NETHERRACK = ARFOBlocks.createBlock(new ARFOSpreadableNetherrackBlock(), "traverse_snowy_cliffs_overgrown_netherrack");
    public static final Block TRAVERSE_CONIFEROUS_FOREST_OVERGROWN_NETHERRACK = ARFOBlocks.createBlock(new ARFOSpreadableNetherrackBlock(), "traverse_coniferous_forest_overgrown_netherrack");
    public static final Block TRAVERSE_SNOWY_CONIFEROUS_FOREST_OVERGROWN_NETHERRACK = ARFOBlocks.createBlock(new ARFOSpreadableNetherrackBlock(), "traverse_snowy_coniferous_forest_overgrown_netherrack");
    public static final Block TRAVERSE_LUSH_SWAMP_OVERGROWN_NETHERRACK = ARFOBlocks.createBlock(new ARFOSpreadableNetherrackBlock(), "traverse_lush_swamp_overgrown_netherrack");
    public static final Block TRAVERSE_PLAINS_PLATEAU_OVERGROWN_NETHERRACK = ARFOBlocks.createBlock(new ARFOSpreadableNetherrackBlock(), "traverse_plains_plateau_overgrown_netherrack");
    public static final Block TRAVERSE_ROLLING_HILLS_OVERGROWN_NETHERRACK = ARFOBlocks.createBlock(new ARFOSpreadableNetherrackBlock(), "traverse_rolling_hills_overgrown_netherrack");
    public static final Block TRAVERSE_MEADOW_OVERGROWN_NETHERRACK = ARFOBlocks.createBlock(new ARFOSpreadableNetherrackBlock(), "traverse_meadow_overgrown_netherrack");
    public static final Block TRAVERSE_WOODED_ISLAND_OVERGROWN_NETHERRACK = ARFOBlocks.createBlock(new ARFOSpreadableNetherrackBlock(), "traverse_wooded_island_overgrown_netherrack");
    public static final Block TRAVERSE_WOODLANDS_OVERGROWN_NETHERRACK = ARFOBlocks.createBlock(new ARFOSpreadableNetherrackBlock(), "traverse_woodlands_overgrown_netherrack");

    public static final Block TRAVERSE_ARID_HIGHLANDS_OVERGROWN_DACITE = ARFOBlocks.createBlock(new ARFOSpreadableStoneBlock(), "traverse_arid_highlands_overgrown_dacite");
    public static final Block TRAVERSE_AUTUMNAL_WOODS_OVERGROWN_DACITE = ARFOBlocks.createBlock(new ARFOSpreadableStoneBlock(), "traverse_autumnal_woods_overgrown_dacite");
    public static final Block TRAVERSE_CLIFFS_OVERGROWN_DACITE = ARFOBlocks.createBlock(new ARFOSpreadableStoneBlock(), "traverse_cliffs_overgrown_dacite");
    public static final Block TRAVERSE_SNOWY_CLIFFS_OVERGROWN_DACITE = ARFOBlocks.createBlock(new ARFOSpreadableStoneBlock(), "traverse_snowy_cliffs_overgrown_dacite");
    public static final Block TRAVERSE_CONIFEROUS_FOREST_OVERGROWN_DACITE = ARFOBlocks.createBlock(new ARFOSpreadableStoneBlock(), "traverse_coniferous_forest_overgrown_dacite");
    public static final Block TRAVERSE_SNOWY_CONIFEROUS_FOREST_OVERGROWN_DACITE = ARFOBlocks.createBlock(new ARFOSpreadableStoneBlock(), "traverse_snowy_coniferous_forest_overgrown_dacite");
    public static final Block TRAVERSE_LUSH_SWAMP_OVERGROWN_DACITE = ARFOBlocks.createBlock(new ARFOSpreadableStoneBlock(), "traverse_lush_swamp_overgrown_dacite");
    public static final Block TRAVERSE_PLAINS_PLATEAU_OVERGROWN_DACITE = ARFOBlocks.createBlock(new ARFOSpreadableStoneBlock(), "traverse_plains_plateau_overgrown_dacite");
    public static final Block TRAVERSE_ROLLING_HILLS_OVERGROWN_DACITE = ARFOBlocks.createBlock(new ARFOSpreadableStoneBlock(), "traverse_rolling_hills_overgrown_dacite");
    public static final Block TRAVERSE_MEADOW_OVERGROWN_DACITE = ARFOBlocks.createBlock(new ARFOSpreadableStoneBlock(), "traverse_meadow_overgrown_dacite");
    public static final Block TRAVERSE_WOODED_ISLAND_OVERGROWN_DACITE = ARFOBlocks.createBlock(new ARFOSpreadableStoneBlock(), "traverse_wooded_island_overgrown_dacite");
    public static final Block TRAVERSE_WOODLANDS_OVERGROWN_DACITE = ARFOBlocks.createBlock(new ARFOSpreadableStoneBlock(), "traverse_woodlands_overgrown_dacite");

    public static final Block TRAVERSE_ARID_HIGHLANDS_OVERGROWN_DACITE_SLAB = ARFOBlocks.createBlock(new ARFOSpreadableStoneSlab(), "traverse_arid_highlands_overgrown_dacite_slab");
    public static final Block TRAVERSE_AUTUMNAL_WOODS_OVERGROWN_DACITE_SLAB = ARFOBlocks.createBlock(new ARFOSpreadableStoneSlab(), "traverse_autumnal_woods_overgrown_dacite_slab");
    public static final Block TRAVERSE_CLIFFS_OVERGROWN_DACITE_SLAB = ARFOBlocks.createBlock(new ARFOSpreadableStoneSlab(), "traverse_cliffs_overgrown_dacite_slab");
    public static final Block TRAVERSE_SNOWY_CLIFFS_OVERGROWN_DACITE_SLAB = ARFOBlocks.createBlock(new ARFOSpreadableStoneSlab(), "traverse_snowy_cliffs_overgrown_dacite_slab");
    public static final Block TRAVERSE_CONIFEROUS_FOREST_OVERGROWN_DACITE_SLAB = ARFOBlocks.createBlock(new ARFOSpreadableStoneSlab(), "traverse_coniferous_forest_overgrown_dacite_slab");
    public static final Block TRAVERSE_SNOWY_CONIFEROUS_FOREST_OVERGROWN_DACITE_SLAB = ARFOBlocks.createBlock(new ARFOSpreadableStoneSlab(), "traverse_snowy_coniferous_forest_overgrown_dacite_slab");
    public static final Block TRAVERSE_LUSH_SWAMP_OVERGROWN_DACITE_SLAB = ARFOBlocks.createBlock(new ARFOSpreadableStoneSlab(), "traverse_lush_swamp_overgrown_dacite_slab");
    public static final Block TRAVERSE_PLAINS_PLATEAU_OVERGROWN_DACITE_SLAB = ARFOBlocks.createBlock(new ARFOSpreadableStoneSlab(), "traverse_plains_plateau_overgrown_dacite_slab");
    public static final Block TRAVERSE_ROLLING_HILLS_OVERGROWN_DACITE_SLAB = ARFOBlocks.createBlock(new ARFOSpreadableStoneSlab(), "traverse_rolling_hills_overgrown_dacite_slab");
    public static final Block TRAVERSE_MEADOW_OVERGROWN_DACITE_SLAB = ARFOBlocks.createBlock(new ARFOSpreadableStoneSlab(), "traverse_meadow_overgrown_dacite_slab");
    public static final Block TRAVERSE_WOODED_ISLAND_OVERGROWN_DACITE_SLAB = ARFOBlocks.createBlock(new ARFOSpreadableStoneSlab(), "traverse_wooded_island_overgrown_dacite_slab");
    public static final Block TRAVERSE_WOODLANDS_OVERGROWN_DACITE_SLAB = ARFOBlocks.createBlock(new ARFOSpreadableStoneSlab(), "traverse_woodlands_overgrown_dacite_slab");

    public static final Block TRAVERSE_ARID_HIGHLANDS_OVERGROWN_NETHERRACK_SLAB = ARFOBlocks.createBlock(new ARFOSpreadableNetherrackSlab(), "traverse_arid_highlands_overgrown_netherrack_slab");
    public static final Block TRAVERSE_AUTUMNAL_WOODS_OVERGROWN_NETHERRACK_SLAB = ARFOBlocks.createBlock(new ARFOSpreadableNetherrackSlab(), "traverse_autumnal_woods_overgrown_netherrack_slab");
    public static final Block TRAVERSE_CLIFFS_OVERGROWN_NETHERRACK_SLAB = ARFOBlocks.createBlock(new ARFOSpreadableNetherrackSlab(), "traverse_cliffs_overgrown_netherrack_slab");
    public static final Block TRAVERSE_SNOWY_CLIFFS_OVERGROWN_NETHERRACK_SLAB = ARFOBlocks.createBlock(new ARFOSpreadableNetherrackSlab(), "traverse_snowy_cliffs_overgrown_netherrack_slab");
    public static final Block TRAVERSE_CONIFEROUS_FOREST_OVERGROWN_NETHERRACK_SLAB = ARFOBlocks.createBlock(new ARFOSpreadableNetherrackSlab(), "traverse_coniferous_forest_overgrown_netherrack_slab");
    public static final Block TRAVERSE_SNOWY_CONIFEROUS_FOREST_OVERGROWN_NETHERRACK_SLAB = ARFOBlocks.createBlock(new ARFOSpreadableNetherrackSlab(), "traverse_snowy_coniferous_forest_overgrown_netherrack_slab");
    public static final Block TRAVERSE_LUSH_SWAMP_OVERGROWN_NETHERRACK_SLAB = ARFOBlocks.createBlock(new ARFOSpreadableNetherrackSlab(), "traverse_lush_swamp_overgrown_netherrack_slab");
    public static final Block TRAVERSE_PLAINS_PLATEAU_OVERGROWN_NETHERRACK_SLAB = ARFOBlocks.createBlock(new ARFOSpreadableNetherrackSlab(), "traverse_plains_plateau_overgrown_netherrack_slab");
    public static final Block TRAVERSE_ROLLING_HILLS_OVERGROWN_NETHERRACK_SLAB = ARFOBlocks.createBlock(new ARFOSpreadableNetherrackSlab(), "traverse_rolling_hills_overgrown_netherrack_slab");
    public static final Block TRAVERSE_MEADOW_OVERGROWN_NETHERRACK_SLAB = ARFOBlocks.createBlock(new ARFOSpreadableNetherrackSlab(), "traverse_meadow_overgrown_netherrack_slab");
    public static final Block TRAVERSE_WOODED_ISLAND_OVERGROWN_NETHERRACK_SLAB = ARFOBlocks.createBlock(new ARFOSpreadableNetherrackSlab(), "traverse_wooded_island_overgrown_netherrack_slab");
    public static final Block TRAVERSE_WOODLANDS_OVERGROWN_NETHERRACK_SLAB = ARFOBlocks.createBlock(new ARFOSpreadableNetherrackSlab(), "traverse_woodlands_overgrown_netherrack_slab");



}
