package com.finallion.artificialfoliage.compatibilty.Traverse;

import com.finallion.artificialfoliage.compatibilty.CompatItemGroup;
import com.finallion.artificialfoliage.item.ARFODyeItem;
import com.finallion.artificialfoliage.registry.ARFOItems;

import net.minecraft.item.BlockItem;
import net.minecraft.item.BucketItem;
import net.minecraft.item.Item;
import net.minecraft.util.registry.Registry;

public class TraverseItems {

    public static void registerItems() {

    }

    public static final Item TRAVERSE_ARID_HIGHLANDS_GRASS_BLOCK = ARFOItems.createItem(new BlockItem(TraverseBlocks.TRAVERSE_ARID_HIGHLANDS_GRASS_BLOCK, new Item.Settings().group(CompatItemGroup.addons)), Registry.BLOCK.getId(TraverseBlocks.TRAVERSE_ARID_HIGHLANDS_GRASS_BLOCK));
    public static final Item TRAVERSE_ARID_HIGHLANDS_GRASS_SLAB = ARFOItems.createItem(new BlockItem(TraverseBlocks.TRAVERSE_ARID_HIGHLANDS_GRASS_SLAB, new Item.Settings().group(CompatItemGroup.addons)), Registry.BLOCK.getId(TraverseBlocks.TRAVERSE_ARID_HIGHLANDS_GRASS_SLAB));
    public static final Item GLOWING_TRAVERSE_ARID_HIGHLANDS_GRASS_BLOCK = ARFOItems.createItem(new BlockItem(TraverseBlocks.GLOWING_TRAVERSE_ARID_HIGHLANDS_GRASS_BLOCK, new Item.Settings().group(CompatItemGroup.addons)), Registry.BLOCK.getId(TraverseBlocks.GLOWING_TRAVERSE_ARID_HIGHLANDS_GRASS_BLOCK));
    public static final Item TRAVERSE_ARID_HIGHLANDS_JUNGLE_LEAVES = ARFOItems.createItem(new BlockItem(TraverseBlocks.TRAVERSE_ARID_HIGHLANDS_JUNGLE_LEAVES, new Item.Settings().group(CompatItemGroup.addons)), Registry.BLOCK.getId(TraverseBlocks.TRAVERSE_ARID_HIGHLANDS_JUNGLE_LEAVES));
    public static final Item TRAVERSE_ARID_HIGHLANDS_JUNGLE_LEAVES_CARPET = ARFOItems.createItem(new BlockItem(TraverseBlocks.TRAVERSE_ARID_HIGHLANDS_JUNGLE_LEAVES_CARPET, new Item.Settings().group(CompatItemGroup.addons)), Registry.BLOCK.getId(TraverseBlocks.TRAVERSE_ARID_HIGHLANDS_JUNGLE_LEAVES_CARPET));
    public static final Item TRAVERSE_ARID_HIGHLANDS_OAK_LEAVES = ARFOItems.createItem(new BlockItem(TraverseBlocks.TRAVERSE_ARID_HIGHLANDS_OAK_LEAVES, new Item.Settings().group(CompatItemGroup.addons)), Registry.BLOCK.getId(TraverseBlocks.TRAVERSE_ARID_HIGHLANDS_OAK_LEAVES));
    public static final Item TRAVERSE_ARID_HIGHLANDS_OAK_LEAVES_CARPET = ARFOItems.createItem(new BlockItem(TraverseBlocks.TRAVERSE_ARID_HIGHLANDS_OAK_LEAVES_CARPET, new Item.Settings().group(CompatItemGroup.addons)), Registry.BLOCK.getId(TraverseBlocks.TRAVERSE_ARID_HIGHLANDS_OAK_LEAVES_CARPET));
    public static final Item TRAVERSE_ARID_HIGHLANDS_DARK_OAK_LEAVES = ARFOItems.createItem(new BlockItem(TraverseBlocks.TRAVERSE_ARID_HIGHLANDS_DARK_OAK_LEAVES, new Item.Settings().group(CompatItemGroup.addons)), Registry.BLOCK.getId(TraverseBlocks.TRAVERSE_ARID_HIGHLANDS_DARK_OAK_LEAVES));
    public static final Item TRAVERSE_ARID_HIGHLANDS_DARK_OAK_LEAVES_CARPET = ARFOItems.createItem(new BlockItem(TraverseBlocks.TRAVERSE_ARID_HIGHLANDS_DARK_OAK_LEAVES_CARPET, new Item.Settings().group(CompatItemGroup.addons)), Registry.BLOCK.getId(TraverseBlocks.TRAVERSE_ARID_HIGHLANDS_DARK_OAK_LEAVES_CARPET));
    public static final Item TRAVERSE_ARID_HIGHLANDS_ACACIA_LEAVES = ARFOItems.createItem(new BlockItem(TraverseBlocks.TRAVERSE_ARID_HIGHLANDS_ACACIA_LEAVES, new Item.Settings().group(CompatItemGroup.addons)), Registry.BLOCK.getId(TraverseBlocks.TRAVERSE_ARID_HIGHLANDS_ACACIA_LEAVES));
    public static final Item TRAVERSE_ARID_HIGHLANDS_ACACIA_LEAVES_CARPET = ARFOItems.createItem(new BlockItem(TraverseBlocks.TRAVERSE_ARID_HIGHLANDS_ACACIA_LEAVES_CARPET, new Item.Settings().group(CompatItemGroup.addons)), Registry.BLOCK.getId(TraverseBlocks.TRAVERSE_ARID_HIGHLANDS_ACACIA_LEAVES_CARPET));
    public static final Item TRAVERSE_ARID_HIGHLANDS_GRASS = ARFOItems.createItem(new BlockItem(TraverseBlocks.TRAVERSE_ARID_HIGHLANDS_GRASS, new Item.Settings().group(CompatItemGroup.addons)), Registry.BLOCK.getId(TraverseBlocks.TRAVERSE_ARID_HIGHLANDS_GRASS));
    public static final Item TALL_TRAVERSE_ARID_HIGHLANDS_GRASS = ARFOItems.createItem(new BlockItem(TraverseBlocks.TALL_TRAVERSE_ARID_HIGHLANDS_GRASS, new Item.Settings().group(CompatItemGroup.addons)), Registry.BLOCK.getId(TraverseBlocks.TALL_TRAVERSE_ARID_HIGHLANDS_GRASS));
    public static final Item TRAVERSE_ARID_HIGHLANDS_FERN = ARFOItems.createItem(new BlockItem(TraverseBlocks.TRAVERSE_ARID_HIGHLANDS_FERN, new Item.Settings().group(CompatItemGroup.addons)), Registry.BLOCK.getId(TraverseBlocks.TRAVERSE_ARID_HIGHLANDS_FERN));
    public static final Item LARGE_TRAVERSE_ARID_HIGHLANDS_FERN = ARFOItems.createItem(new BlockItem(TraverseBlocks.LARGE_TRAVERSE_ARID_HIGHLANDS_FERN, new Item.Settings().group(CompatItemGroup.addons)), Registry.BLOCK.getId(TraverseBlocks.LARGE_TRAVERSE_ARID_HIGHLANDS_FERN));
    public static final Item TRAVERSE_ARID_HIGHLANDS_SUGAR_CANE = ARFOItems.createItem(new BlockItem(TraverseBlocks.TRAVERSE_ARID_HIGHLANDS_SUGAR_CANE, new Item.Settings().group(CompatItemGroup.addons)), Registry.BLOCK.getId(TraverseBlocks.TRAVERSE_ARID_HIGHLANDS_SUGAR_CANE));
    public static final Item TRAVERSE_ARID_HIGHLANDS_VINE = ARFOItems.createItem(new BlockItem(TraverseBlocks.TRAVERSE_ARID_HIGHLANDS_VINE, new Item.Settings().group(CompatItemGroup.addons)), Registry.BLOCK.getId(TraverseBlocks.TRAVERSE_ARID_HIGHLANDS_VINE));

    public static final Item TRAVERSE_AUTUMNAL_WOODS_GRASS_BLOCK = ARFOItems.createItem(new BlockItem(TraverseBlocks.TRAVERSE_AUTUMNAL_WOODS_GRASS_BLOCK, new Item.Settings().group(CompatItemGroup.addons)), Registry.BLOCK.getId(TraverseBlocks.TRAVERSE_AUTUMNAL_WOODS_GRASS_BLOCK));
    public static final Item TRAVERSE_AUTUMNAL_WOODS_GRASS_SLAB = ARFOItems.createItem(new BlockItem(TraverseBlocks.TRAVERSE_AUTUMNAL_WOODS_GRASS_SLAB, new Item.Settings().group(CompatItemGroup.addons)), Registry.BLOCK.getId(TraverseBlocks.TRAVERSE_AUTUMNAL_WOODS_GRASS_SLAB));
    public static final Item GLOWING_TRAVERSE_AUTUMNAL_WOODS_GRASS_BLOCK = ARFOItems.createItem(new BlockItem(TraverseBlocks.GLOWING_TRAVERSE_AUTUMNAL_WOODS_GRASS_BLOCK, new Item.Settings().group(CompatItemGroup.addons)), Registry.BLOCK.getId(TraverseBlocks.GLOWING_TRAVERSE_AUTUMNAL_WOODS_GRASS_BLOCK));
    public static final Item TRAVERSE_AUTUMNAL_WOODS_JUNGLE_LEAVES = ARFOItems.createItem(new BlockItem(TraverseBlocks.TRAVERSE_AUTUMNAL_WOODS_JUNGLE_LEAVES, new Item.Settings().group(CompatItemGroup.addons)), Registry.BLOCK.getId(TraverseBlocks.TRAVERSE_AUTUMNAL_WOODS_JUNGLE_LEAVES));
    public static final Item TRAVERSE_AUTUMNAL_WOODS_JUNGLE_LEAVES_CARPET = ARFOItems.createItem(new BlockItem(TraverseBlocks.TRAVERSE_AUTUMNAL_WOODS_JUNGLE_LEAVES_CARPET, new Item.Settings().group(CompatItemGroup.addons)), Registry.BLOCK.getId(TraverseBlocks.TRAVERSE_AUTUMNAL_WOODS_JUNGLE_LEAVES_CARPET));
    public static final Item TRAVERSE_AUTUMNAL_WOODS_OAK_LEAVES = ARFOItems.createItem(new BlockItem(TraverseBlocks.TRAVERSE_AUTUMNAL_WOODS_OAK_LEAVES, new Item.Settings().group(CompatItemGroup.addons)), Registry.BLOCK.getId(TraverseBlocks.TRAVERSE_AUTUMNAL_WOODS_OAK_LEAVES));
    public static final Item TRAVERSE_AUTUMNAL_WOODS_OAK_LEAVES_CARPET = ARFOItems.createItem(new BlockItem(TraverseBlocks.TRAVERSE_AUTUMNAL_WOODS_OAK_LEAVES_CARPET, new Item.Settings().group(CompatItemGroup.addons)), Registry.BLOCK.getId(TraverseBlocks.TRAVERSE_AUTUMNAL_WOODS_OAK_LEAVES_CARPET));
    public static final Item TRAVERSE_AUTUMNAL_WOODS_DARK_OAK_LEAVES = ARFOItems.createItem(new BlockItem(TraverseBlocks.TRAVERSE_AUTUMNAL_WOODS_DARK_OAK_LEAVES, new Item.Settings().group(CompatItemGroup.addons)), Registry.BLOCK.getId(TraverseBlocks.TRAVERSE_AUTUMNAL_WOODS_DARK_OAK_LEAVES));
    public static final Item TRAVERSE_AUTUMNAL_WOODS_DARK_OAK_LEAVES_CARPET = ARFOItems.createItem(new BlockItem(TraverseBlocks.TRAVERSE_AUTUMNAL_WOODS_DARK_OAK_LEAVES_CARPET, new Item.Settings().group(CompatItemGroup.addons)), Registry.BLOCK.getId(TraverseBlocks.TRAVERSE_AUTUMNAL_WOODS_DARK_OAK_LEAVES_CARPET));
    public static final Item TRAVERSE_AUTUMNAL_WOODS_ACACIA_LEAVES = ARFOItems.createItem(new BlockItem(TraverseBlocks.TRAVERSE_AUTUMNAL_WOODS_ACACIA_LEAVES, new Item.Settings().group(CompatItemGroup.addons)), Registry.BLOCK.getId(TraverseBlocks.TRAVERSE_AUTUMNAL_WOODS_ACACIA_LEAVES));
    public static final Item TRAVERSE_AUTUMNAL_WOODS_ACACIA_LEAVES_CARPET = ARFOItems.createItem(new BlockItem(TraverseBlocks.TRAVERSE_AUTUMNAL_WOODS_ACACIA_LEAVES_CARPET, new Item.Settings().group(CompatItemGroup.addons)), Registry.BLOCK.getId(TraverseBlocks.TRAVERSE_AUTUMNAL_WOODS_ACACIA_LEAVES_CARPET));
    public static final Item TRAVERSE_AUTUMNAL_WOODS_GRASS = ARFOItems.createItem(new BlockItem(TraverseBlocks.TRAVERSE_AUTUMNAL_WOODS_GRASS, new Item.Settings().group(CompatItemGroup.addons)), Registry.BLOCK.getId(TraverseBlocks.TRAVERSE_AUTUMNAL_WOODS_GRASS));
    public static final Item TALL_TRAVERSE_AUTUMNAL_WOODS_GRASS = ARFOItems.createItem(new BlockItem(TraverseBlocks.TALL_TRAVERSE_AUTUMNAL_WOODS_GRASS, new Item.Settings().group(CompatItemGroup.addons)), Registry.BLOCK.getId(TraverseBlocks.TALL_TRAVERSE_AUTUMNAL_WOODS_GRASS));
    public static final Item TRAVERSE_AUTUMNAL_WOODS_FERN = ARFOItems.createItem(new BlockItem(TraverseBlocks.TRAVERSE_AUTUMNAL_WOODS_FERN, new Item.Settings().group(CompatItemGroup.addons)), Registry.BLOCK.getId(TraverseBlocks.TRAVERSE_AUTUMNAL_WOODS_FERN));
    public static final Item LARGE_TRAVERSE_AUTUMNAL_WOODS_FERN = ARFOItems.createItem(new BlockItem(TraverseBlocks.LARGE_TRAVERSE_AUTUMNAL_WOODS_FERN, new Item.Settings().group(CompatItemGroup.addons)), Registry.BLOCK.getId(TraverseBlocks.LARGE_TRAVERSE_AUTUMNAL_WOODS_FERN));
    public static final Item TRAVERSE_AUTUMNAL_WOODS_SUGAR_CANE = ARFOItems.createItem(new BlockItem(TraverseBlocks.TRAVERSE_AUTUMNAL_WOODS_SUGAR_CANE, new Item.Settings().group(CompatItemGroup.addons)), Registry.BLOCK.getId(TraverseBlocks.TRAVERSE_AUTUMNAL_WOODS_SUGAR_CANE));
    public static final Item TRAVERSE_AUTUMNAL_WOODS_VINE = ARFOItems.createItem(new BlockItem(TraverseBlocks.TRAVERSE_AUTUMNAL_WOODS_VINE, new Item.Settings().group(CompatItemGroup.addons)), Registry.BLOCK.getId(TraverseBlocks.TRAVERSE_AUTUMNAL_WOODS_VINE));


    public static final Item TRAVERSE_CLIFFS_GRASS_BLOCK = ARFOItems.createItem(new BlockItem(TraverseBlocks.TRAVERSE_CLIFFS_GRASS_BLOCK, new Item.Settings().group(CompatItemGroup.addons)), Registry.BLOCK.getId(TraverseBlocks.TRAVERSE_CLIFFS_GRASS_BLOCK));
    public static final Item TRAVERSE_CLIFFS_GRASS_SLAB = ARFOItems.createItem(new BlockItem(TraverseBlocks.TRAVERSE_CLIFFS_GRASS_SLAB, new Item.Settings().group(CompatItemGroup.addons)), Registry.BLOCK.getId(TraverseBlocks.TRAVERSE_CLIFFS_GRASS_SLAB));
    public static final Item GLOWING_TRAVERSE_CLIFFS_GRASS_BLOCK = ARFOItems.createItem(new BlockItem(TraverseBlocks.GLOWING_TRAVERSE_CLIFFS_GRASS_BLOCK, new Item.Settings().group(CompatItemGroup.addons)), Registry.BLOCK.getId(TraverseBlocks.GLOWING_TRAVERSE_CLIFFS_GRASS_BLOCK));
    public static final Item TRAVERSE_CLIFFS_JUNGLE_LEAVES = ARFOItems.createItem(new BlockItem(TraverseBlocks.TRAVERSE_CLIFFS_JUNGLE_LEAVES, new Item.Settings().group(CompatItemGroup.addons)), Registry.BLOCK.getId(TraverseBlocks.TRAVERSE_CLIFFS_JUNGLE_LEAVES));
    public static final Item TRAVERSE_CLIFFS_JUNGLE_LEAVES_CARPET = ARFOItems.createItem(new BlockItem(TraverseBlocks.TRAVERSE_CLIFFS_JUNGLE_LEAVES_CARPET, new Item.Settings().group(CompatItemGroup.addons)), Registry.BLOCK.getId(TraverseBlocks.TRAVERSE_CLIFFS_JUNGLE_LEAVES_CARPET));
    public static final Item TRAVERSE_CLIFFS_OAK_LEAVES = ARFOItems.createItem(new BlockItem(TraverseBlocks.TRAVERSE_CLIFFS_OAK_LEAVES, new Item.Settings().group(CompatItemGroup.addons)), Registry.BLOCK.getId(TraverseBlocks.TRAVERSE_CLIFFS_OAK_LEAVES));
    public static final Item TRAVERSE_CLIFFS_OAK_LEAVES_CARPET = ARFOItems.createItem(new BlockItem(TraverseBlocks.TRAVERSE_CLIFFS_OAK_LEAVES_CARPET, new Item.Settings().group(CompatItemGroup.addons)), Registry.BLOCK.getId(TraverseBlocks.TRAVERSE_CLIFFS_OAK_LEAVES_CARPET));
    public static final Item TRAVERSE_CLIFFS_DARK_OAK_LEAVES = ARFOItems.createItem(new BlockItem(TraverseBlocks.TRAVERSE_CLIFFS_DARK_OAK_LEAVES, new Item.Settings().group(CompatItemGroup.addons)), Registry.BLOCK.getId(TraverseBlocks.TRAVERSE_CLIFFS_DARK_OAK_LEAVES));
    public static final Item TRAVERSE_CLIFFS_DARK_OAK_LEAVES_CARPET = ARFOItems.createItem(new BlockItem(TraverseBlocks.TRAVERSE_CLIFFS_DARK_OAK_LEAVES_CARPET, new Item.Settings().group(CompatItemGroup.addons)), Registry.BLOCK.getId(TraverseBlocks.TRAVERSE_CLIFFS_DARK_OAK_LEAVES_CARPET));
    public static final Item TRAVERSE_CLIFFS_ACACIA_LEAVES = ARFOItems.createItem(new BlockItem(TraverseBlocks.TRAVERSE_CLIFFS_ACACIA_LEAVES, new Item.Settings().group(CompatItemGroup.addons)), Registry.BLOCK.getId(TraverseBlocks.TRAVERSE_CLIFFS_ACACIA_LEAVES));
    public static final Item TRAVERSE_CLIFFS_ACACIA_LEAVES_CARPET = ARFOItems.createItem(new BlockItem(TraverseBlocks.TRAVERSE_CLIFFS_ACACIA_LEAVES_CARPET, new Item.Settings().group(CompatItemGroup.addons)), Registry.BLOCK.getId(TraverseBlocks.TRAVERSE_CLIFFS_ACACIA_LEAVES_CARPET));
    public static final Item TRAVERSE_CLIFFS_GRASS = ARFOItems.createItem(new BlockItem(TraverseBlocks.TRAVERSE_CLIFFS_GRASS, new Item.Settings().group(CompatItemGroup.addons)), Registry.BLOCK.getId(TraverseBlocks.TRAVERSE_CLIFFS_GRASS));
    public static final Item TALL_TRAVERSE_CLIFFS_GRASS = ARFOItems.createItem(new BlockItem(TraverseBlocks.TALL_TRAVERSE_CLIFFS_GRASS, new Item.Settings().group(CompatItemGroup.addons)), Registry.BLOCK.getId(TraverseBlocks.TALL_TRAVERSE_CLIFFS_GRASS));
    public static final Item TRAVERSE_CLIFFS_FERN = ARFOItems.createItem(new BlockItem(TraverseBlocks.TRAVERSE_CLIFFS_FERN, new Item.Settings().group(CompatItemGroup.addons)), Registry.BLOCK.getId(TraverseBlocks.TRAVERSE_CLIFFS_FERN));
    public static final Item LARGE_TRAVERSE_CLIFFS_FERN = ARFOItems.createItem(new BlockItem(TraverseBlocks.LARGE_TRAVERSE_CLIFFS_FERN, new Item.Settings().group(CompatItemGroup.addons)), Registry.BLOCK.getId(TraverseBlocks.LARGE_TRAVERSE_CLIFFS_FERN));
    public static final Item TRAVERSE_CLIFFS_SUGAR_CANE = ARFOItems.createItem(new BlockItem(TraverseBlocks.TRAVERSE_CLIFFS_SUGAR_CANE, new Item.Settings().group(CompatItemGroup.addons)), Registry.BLOCK.getId(TraverseBlocks.TRAVERSE_CLIFFS_SUGAR_CANE));
    public static final Item TRAVERSE_CLIFFS_VINE = ARFOItems.createItem(new BlockItem(TraverseBlocks.TRAVERSE_CLIFFS_VINE, new Item.Settings().group(CompatItemGroup.addons)), Registry.BLOCK.getId(TraverseBlocks.TRAVERSE_CLIFFS_VINE));


    public static final Item TRAVERSE_SNOWY_CLIFFS_GRASS_BLOCK = ARFOItems.createItem(new BlockItem(TraverseBlocks.TRAVERSE_SNOWY_CLIFFS_GRASS_BLOCK, new Item.Settings().group(CompatItemGroup.addons)), Registry.BLOCK.getId(TraverseBlocks.TRAVERSE_SNOWY_CLIFFS_GRASS_BLOCK));
    public static final Item TRAVERSE_SNOWY_CLIFFS_GRASS_SLAB = ARFOItems.createItem(new BlockItem(TraverseBlocks.TRAVERSE_SNOWY_CLIFFS_GRASS_SLAB, new Item.Settings().group(CompatItemGroup.addons)), Registry.BLOCK.getId(TraverseBlocks.TRAVERSE_SNOWY_CLIFFS_GRASS_SLAB));
    public static final Item GLOWING_TRAVERSE_SNOWY_CLIFFS_GRASS_BLOCK = ARFOItems.createItem(new BlockItem(TraverseBlocks.GLOWING_TRAVERSE_SNOWY_CLIFFS_GRASS_BLOCK, new Item.Settings().group(CompatItemGroup.addons)), Registry.BLOCK.getId(TraverseBlocks.GLOWING_TRAVERSE_SNOWY_CLIFFS_GRASS_BLOCK));
    public static final Item TRAVERSE_SNOWY_CLIFFS_JUNGLE_LEAVES = ARFOItems.createItem(new BlockItem(TraverseBlocks.TRAVERSE_SNOWY_CLIFFS_JUNGLE_LEAVES, new Item.Settings().group(CompatItemGroup.addons)), Registry.BLOCK.getId(TraverseBlocks.TRAVERSE_SNOWY_CLIFFS_JUNGLE_LEAVES));
    public static final Item TRAVERSE_SNOWY_CLIFFS_JUNGLE_LEAVES_CARPET = ARFOItems.createItem(new BlockItem(TraverseBlocks.TRAVERSE_SNOWY_CLIFFS_JUNGLE_LEAVES_CARPET, new Item.Settings().group(CompatItemGroup.addons)), Registry.BLOCK.getId(TraverseBlocks.TRAVERSE_SNOWY_CLIFFS_JUNGLE_LEAVES_CARPET));
    public static final Item TRAVERSE_SNOWY_CLIFFS_OAK_LEAVES = ARFOItems.createItem(new BlockItem(TraverseBlocks.TRAVERSE_SNOWY_CLIFFS_OAK_LEAVES, new Item.Settings().group(CompatItemGroup.addons)), Registry.BLOCK.getId(TraverseBlocks.TRAVERSE_SNOWY_CLIFFS_OAK_LEAVES));
    public static final Item TRAVERSE_SNOWY_CLIFFS_OAK_LEAVES_CARPET = ARFOItems.createItem(new BlockItem(TraverseBlocks.TRAVERSE_SNOWY_CLIFFS_OAK_LEAVES_CARPET, new Item.Settings().group(CompatItemGroup.addons)), Registry.BLOCK.getId(TraverseBlocks.TRAVERSE_SNOWY_CLIFFS_OAK_LEAVES_CARPET));
    public static final Item TRAVERSE_SNOWY_CLIFFS_DARK_OAK_LEAVES = ARFOItems.createItem(new BlockItem(TraverseBlocks.TRAVERSE_SNOWY_CLIFFS_DARK_OAK_LEAVES, new Item.Settings().group(CompatItemGroup.addons)), Registry.BLOCK.getId(TraverseBlocks.TRAVERSE_SNOWY_CLIFFS_DARK_OAK_LEAVES));
    public static final Item TRAVERSE_SNOWY_CLIFFS_DARK_OAK_LEAVES_CARPET = ARFOItems.createItem(new BlockItem(TraverseBlocks.TRAVERSE_SNOWY_CLIFFS_DARK_OAK_LEAVES_CARPET, new Item.Settings().group(CompatItemGroup.addons)), Registry.BLOCK.getId(TraverseBlocks.TRAVERSE_SNOWY_CLIFFS_DARK_OAK_LEAVES_CARPET));
    public static final Item TRAVERSE_SNOWY_CLIFFS_ACACIA_LEAVES = ARFOItems.createItem(new BlockItem(TraverseBlocks.TRAVERSE_SNOWY_CLIFFS_ACACIA_LEAVES, new Item.Settings().group(CompatItemGroup.addons)), Registry.BLOCK.getId(TraverseBlocks.TRAVERSE_SNOWY_CLIFFS_ACACIA_LEAVES));
    public static final Item TRAVERSE_SNOWY_CLIFFS_ACACIA_LEAVES_CARPET = ARFOItems.createItem(new BlockItem(TraverseBlocks.TRAVERSE_SNOWY_CLIFFS_ACACIA_LEAVES_CARPET, new Item.Settings().group(CompatItemGroup.addons)), Registry.BLOCK.getId(TraverseBlocks.TRAVERSE_SNOWY_CLIFFS_ACACIA_LEAVES_CARPET));
    public static final Item TRAVERSE_SNOWY_CLIFFS_GRASS = ARFOItems.createItem(new BlockItem(TraverseBlocks.TRAVERSE_SNOWY_CLIFFS_GRASS, new Item.Settings().group(CompatItemGroup.addons)), Registry.BLOCK.getId(TraverseBlocks.TRAVERSE_SNOWY_CLIFFS_GRASS));
    public static final Item TALL_TRAVERSE_SNOWY_CLIFFS_GRASS = ARFOItems.createItem(new BlockItem(TraverseBlocks.TALL_TRAVERSE_SNOWY_CLIFFS_GRASS, new Item.Settings().group(CompatItemGroup.addons)), Registry.BLOCK.getId(TraverseBlocks.TALL_TRAVERSE_SNOWY_CLIFFS_GRASS));
    public static final Item TRAVERSE_SNOWY_CLIFFS_FERN = ARFOItems.createItem(new BlockItem(TraverseBlocks.TRAVERSE_SNOWY_CLIFFS_FERN, new Item.Settings().group(CompatItemGroup.addons)), Registry.BLOCK.getId(TraverseBlocks.TRAVERSE_SNOWY_CLIFFS_FERN));
    public static final Item LARGE_TRAVERSE_SNOWY_CLIFFS_FERN = ARFOItems.createItem(new BlockItem(TraverseBlocks.LARGE_TRAVERSE_SNOWY_CLIFFS_FERN, new Item.Settings().group(CompatItemGroup.addons)), Registry.BLOCK.getId(TraverseBlocks.LARGE_TRAVERSE_SNOWY_CLIFFS_FERN));
    public static final Item TRAVERSE_SNOWY_CLIFFS_SUGAR_CANE = ARFOItems.createItem(new BlockItem(TraverseBlocks.TRAVERSE_SNOWY_CLIFFS_SUGAR_CANE, new Item.Settings().group(CompatItemGroup.addons)), Registry.BLOCK.getId(TraverseBlocks.TRAVERSE_SNOWY_CLIFFS_SUGAR_CANE));
    public static final Item TRAVERSE_SNOWY_CLIFFS_VINE = ARFOItems.createItem(new BlockItem(TraverseBlocks.TRAVERSE_SNOWY_CLIFFS_VINE, new Item.Settings().group(CompatItemGroup.addons)), Registry.BLOCK.getId(TraverseBlocks.TRAVERSE_SNOWY_CLIFFS_VINE));

    public static final Item TRAVERSE_CONIFEROUS_FOREST_GRASS_BLOCK = ARFOItems.createItem(new BlockItem(TraverseBlocks.TRAVERSE_CONIFEROUS_FOREST_GRASS_BLOCK, new Item.Settings().group(CompatItemGroup.addons)), Registry.BLOCK.getId(TraverseBlocks.TRAVERSE_CONIFEROUS_FOREST_GRASS_BLOCK));
    public static final Item TRAVERSE_CONIFEROUS_FOREST_GRASS_SLAB = ARFOItems.createItem(new BlockItem(TraverseBlocks.TRAVERSE_CONIFEROUS_FOREST_GRASS_SLAB, new Item.Settings().group(CompatItemGroup.addons)), Registry.BLOCK.getId(TraverseBlocks.TRAVERSE_CONIFEROUS_FOREST_GRASS_SLAB));
    public static final Item GLOWING_TRAVERSE_CONIFEROUS_FOREST_GRASS_BLOCK = ARFOItems.createItem(new BlockItem(TraverseBlocks.GLOWING_TRAVERSE_CONIFEROUS_FOREST_GRASS_BLOCK, new Item.Settings().group(CompatItemGroup.addons)), Registry.BLOCK.getId(TraverseBlocks.GLOWING_TRAVERSE_CONIFEROUS_FOREST_GRASS_BLOCK));
    public static final Item TRAVERSE_CONIFEROUS_FOREST_JUNGLE_LEAVES = ARFOItems.createItem(new BlockItem(TraverseBlocks.TRAVERSE_CONIFEROUS_FOREST_JUNGLE_LEAVES, new Item.Settings().group(CompatItemGroup.addons)), Registry.BLOCK.getId(TraverseBlocks.TRAVERSE_CONIFEROUS_FOREST_JUNGLE_LEAVES));
    public static final Item TRAVERSE_CONIFEROUS_FOREST_JUNGLE_LEAVES_CARPET = ARFOItems.createItem(new BlockItem(TraverseBlocks.TRAVERSE_CONIFEROUS_FOREST_JUNGLE_LEAVES_CARPET, new Item.Settings().group(CompatItemGroup.addons)), Registry.BLOCK.getId(TraverseBlocks.TRAVERSE_CONIFEROUS_FOREST_JUNGLE_LEAVES_CARPET));
    public static final Item TRAVERSE_CONIFEROUS_FOREST_OAK_LEAVES = ARFOItems.createItem(new BlockItem(TraverseBlocks.TRAVERSE_CONIFEROUS_FOREST_OAK_LEAVES, new Item.Settings().group(CompatItemGroup.addons)), Registry.BLOCK.getId(TraverseBlocks.TRAVERSE_CONIFEROUS_FOREST_OAK_LEAVES));
    public static final Item TRAVERSE_CONIFEROUS_FOREST_OAK_LEAVES_CARPET = ARFOItems.createItem(new BlockItem(TraverseBlocks.TRAVERSE_CONIFEROUS_FOREST_OAK_LEAVES_CARPET, new Item.Settings().group(CompatItemGroup.addons)), Registry.BLOCK.getId(TraverseBlocks.TRAVERSE_CONIFEROUS_FOREST_OAK_LEAVES_CARPET));
    public static final Item TRAVERSE_CONIFEROUS_FOREST_DARK_OAK_LEAVES = ARFOItems.createItem(new BlockItem(TraverseBlocks.TRAVERSE_CONIFEROUS_FOREST_DARK_OAK_LEAVES, new Item.Settings().group(CompatItemGroup.addons)), Registry.BLOCK.getId(TraverseBlocks.TRAVERSE_CONIFEROUS_FOREST_DARK_OAK_LEAVES));
    public static final Item TRAVERSE_CONIFEROUS_FOREST_DARK_OAK_LEAVES_CARPET = ARFOItems.createItem(new BlockItem(TraverseBlocks.TRAVERSE_CONIFEROUS_FOREST_DARK_OAK_LEAVES_CARPET, new Item.Settings().group(CompatItemGroup.addons)), Registry.BLOCK.getId(TraverseBlocks.TRAVERSE_CONIFEROUS_FOREST_DARK_OAK_LEAVES_CARPET));
    public static final Item TRAVERSE_CONIFEROUS_FOREST_ACACIA_LEAVES = ARFOItems.createItem(new BlockItem(TraverseBlocks.TRAVERSE_CONIFEROUS_FOREST_ACACIA_LEAVES, new Item.Settings().group(CompatItemGroup.addons)), Registry.BLOCK.getId(TraverseBlocks.TRAVERSE_CONIFEROUS_FOREST_ACACIA_LEAVES));
    public static final Item TRAVERSE_CONIFEROUS_FOREST_ACACIA_LEAVES_CARPET = ARFOItems.createItem(new BlockItem(TraverseBlocks.TRAVERSE_CONIFEROUS_FOREST_ACACIA_LEAVES_CARPET, new Item.Settings().group(CompatItemGroup.addons)), Registry.BLOCK.getId(TraverseBlocks.TRAVERSE_CONIFEROUS_FOREST_ACACIA_LEAVES_CARPET));
    public static final Item TRAVERSE_CONIFEROUS_FOREST_GRASS = ARFOItems.createItem(new BlockItem(TraverseBlocks.TRAVERSE_CONIFEROUS_FOREST_GRASS, new Item.Settings().group(CompatItemGroup.addons)), Registry.BLOCK.getId(TraverseBlocks.TRAVERSE_CONIFEROUS_FOREST_GRASS));
    public static final Item TALL_TRAVERSE_CONIFEROUS_FOREST_GRASS = ARFOItems.createItem(new BlockItem(TraverseBlocks.TALL_TRAVERSE_CONIFEROUS_FOREST_GRASS, new Item.Settings().group(CompatItemGroup.addons)), Registry.BLOCK.getId(TraverseBlocks.TALL_TRAVERSE_CONIFEROUS_FOREST_GRASS));
    public static final Item TRAVERSE_CONIFEROUS_FOREST_FERN = ARFOItems.createItem(new BlockItem(TraverseBlocks.TRAVERSE_CONIFEROUS_FOREST_FERN, new Item.Settings().group(CompatItemGroup.addons)), Registry.BLOCK.getId(TraverseBlocks.TRAVERSE_CONIFEROUS_FOREST_FERN));
    public static final Item LARGE_TRAVERSE_CONIFEROUS_FOREST_FERN = ARFOItems.createItem(new BlockItem(TraverseBlocks.LARGE_TRAVERSE_CONIFEROUS_FOREST_FERN, new Item.Settings().group(CompatItemGroup.addons)), Registry.BLOCK.getId(TraverseBlocks.LARGE_TRAVERSE_CONIFEROUS_FOREST_FERN));
    public static final Item TRAVERSE_CONIFEROUS_FOREST_SUGAR_CANE = ARFOItems.createItem(new BlockItem(TraverseBlocks.TRAVERSE_CONIFEROUS_FOREST_SUGAR_CANE, new Item.Settings().group(CompatItemGroup.addons)), Registry.BLOCK.getId(TraverseBlocks.TRAVERSE_CONIFEROUS_FOREST_SUGAR_CANE));
    public static final Item TRAVERSE_CONIFEROUS_FOREST_VINE = ARFOItems.createItem(new BlockItem(TraverseBlocks.TRAVERSE_CONIFEROUS_FOREST_VINE, new Item.Settings().group(CompatItemGroup.addons)), Registry.BLOCK.getId(TraverseBlocks.TRAVERSE_CONIFEROUS_FOREST_VINE));

    public static final Item TRAVERSE_SNOWY_CONIFEROUS_FOREST_GRASS_BLOCK = ARFOItems.createItem(new BlockItem(TraverseBlocks.TRAVERSE_SNOWY_CONIFEROUS_FOREST_GRASS_BLOCK, new Item.Settings().group(CompatItemGroup.addons)), Registry.BLOCK.getId(TraverseBlocks.TRAVERSE_SNOWY_CONIFEROUS_FOREST_GRASS_BLOCK));
    public static final Item TRAVERSE_SNOWY_CONIFEROUS_FOREST_GRASS_SLAB = ARFOItems.createItem(new BlockItem(TraverseBlocks.TRAVERSE_SNOWY_CONIFEROUS_FOREST_GRASS_SLAB, new Item.Settings().group(CompatItemGroup.addons)), Registry.BLOCK.getId(TraverseBlocks.TRAVERSE_SNOWY_CONIFEROUS_FOREST_GRASS_SLAB));
    public static final Item GLOWING_TRAVERSE_SNOWY_CONIFEROUS_FOREST_GRASS_BLOCK = ARFOItems.createItem(new BlockItem(TraverseBlocks.GLOWING_TRAVERSE_SNOWY_CONIFEROUS_FOREST_GRASS_BLOCK, new Item.Settings().group(CompatItemGroup.addons)), Registry.BLOCK.getId(TraverseBlocks.GLOWING_TRAVERSE_SNOWY_CONIFEROUS_FOREST_GRASS_BLOCK));
    public static final Item TRAVERSE_SNOWY_CONIFEROUS_FOREST_JUNGLE_LEAVES = ARFOItems.createItem(new BlockItem(TraverseBlocks.TRAVERSE_SNOWY_CONIFEROUS_FOREST_JUNGLE_LEAVES, new Item.Settings().group(CompatItemGroup.addons)), Registry.BLOCK.getId(TraverseBlocks.TRAVERSE_SNOWY_CONIFEROUS_FOREST_JUNGLE_LEAVES));
    public static final Item TRAVERSE_SNOWY_CONIFEROUS_FOREST_JUNGLE_LEAVES_CARPET = ARFOItems.createItem(new BlockItem(TraverseBlocks.TRAVERSE_SNOWY_CONIFEROUS_FOREST_JUNGLE_LEAVES_CARPET, new Item.Settings().group(CompatItemGroup.addons)), Registry.BLOCK.getId(TraverseBlocks.TRAVERSE_SNOWY_CONIFEROUS_FOREST_JUNGLE_LEAVES_CARPET));
    public static final Item TRAVERSE_SNOWY_CONIFEROUS_FOREST_OAK_LEAVES = ARFOItems.createItem(new BlockItem(TraverseBlocks.TRAVERSE_SNOWY_CONIFEROUS_FOREST_OAK_LEAVES, new Item.Settings().group(CompatItemGroup.addons)), Registry.BLOCK.getId(TraverseBlocks.TRAVERSE_SNOWY_CONIFEROUS_FOREST_OAK_LEAVES));
    public static final Item TRAVERSE_SNOWY_CONIFEROUS_FOREST_OAK_LEAVES_CARPET = ARFOItems.createItem(new BlockItem(TraverseBlocks.TRAVERSE_SNOWY_CONIFEROUS_FOREST_OAK_LEAVES_CARPET, new Item.Settings().group(CompatItemGroup.addons)), Registry.BLOCK.getId(TraverseBlocks.TRAVERSE_SNOWY_CONIFEROUS_FOREST_OAK_LEAVES_CARPET));
    public static final Item TRAVERSE_SNOWY_CONIFEROUS_FOREST_DARK_OAK_LEAVES = ARFOItems.createItem(new BlockItem(TraverseBlocks.TRAVERSE_SNOWY_CONIFEROUS_FOREST_DARK_OAK_LEAVES, new Item.Settings().group(CompatItemGroup.addons)), Registry.BLOCK.getId(TraverseBlocks.TRAVERSE_SNOWY_CONIFEROUS_FOREST_DARK_OAK_LEAVES));
    public static final Item TRAVERSE_SNOWY_CONIFEROUS_FOREST_DARK_OAK_LEAVES_CARPET = ARFOItems.createItem(new BlockItem(TraverseBlocks.TRAVERSE_SNOWY_CONIFEROUS_FOREST_DARK_OAK_LEAVES_CARPET, new Item.Settings().group(CompatItemGroup.addons)), Registry.BLOCK.getId(TraverseBlocks.TRAVERSE_SNOWY_CONIFEROUS_FOREST_DARK_OAK_LEAVES_CARPET));
    public static final Item TRAVERSE_SNOWY_CONIFEROUS_FOREST_ACACIA_LEAVES = ARFOItems.createItem(new BlockItem(TraverseBlocks.TRAVERSE_SNOWY_CONIFEROUS_FOREST_ACACIA_LEAVES, new Item.Settings().group(CompatItemGroup.addons)), Registry.BLOCK.getId(TraverseBlocks.TRAVERSE_SNOWY_CONIFEROUS_FOREST_ACACIA_LEAVES));
    public static final Item TRAVERSE_SNOWY_CONIFEROUS_FOREST_ACACIA_LEAVES_CARPET = ARFOItems.createItem(new BlockItem(TraverseBlocks.TRAVERSE_SNOWY_CONIFEROUS_FOREST_ACACIA_LEAVES_CARPET, new Item.Settings().group(CompatItemGroup.addons)), Registry.BLOCK.getId(TraverseBlocks.TRAVERSE_SNOWY_CONIFEROUS_FOREST_ACACIA_LEAVES_CARPET));
    public static final Item TRAVERSE_SNOWY_CONIFEROUS_FOREST_GRASS = ARFOItems.createItem(new BlockItem(TraverseBlocks.TRAVERSE_SNOWY_CONIFEROUS_FOREST_GRASS, new Item.Settings().group(CompatItemGroup.addons)), Registry.BLOCK.getId(TraverseBlocks.TRAVERSE_SNOWY_CONIFEROUS_FOREST_GRASS));
    public static final Item TALL_TRAVERSE_SNOWY_CONIFEROUS_FOREST_GRASS = ARFOItems.createItem(new BlockItem(TraverseBlocks.TALL_TRAVERSE_SNOWY_CONIFEROUS_FOREST_GRASS, new Item.Settings().group(CompatItemGroup.addons)), Registry.BLOCK.getId(TraverseBlocks.TALL_TRAVERSE_SNOWY_CONIFEROUS_FOREST_GRASS));
    public static final Item TRAVERSE_SNOWY_CONIFEROUS_FOREST_FERN = ARFOItems.createItem(new BlockItem(TraverseBlocks.TRAVERSE_SNOWY_CONIFEROUS_FOREST_FERN, new Item.Settings().group(CompatItemGroup.addons)), Registry.BLOCK.getId(TraverseBlocks.TRAVERSE_SNOWY_CONIFEROUS_FOREST_FERN));
    public static final Item LARGE_TRAVERSE_SNOWY_CONIFEROUS_FOREST_FERN = ARFOItems.createItem(new BlockItem(TraverseBlocks.LARGE_TRAVERSE_SNOWY_CONIFEROUS_FOREST_FERN, new Item.Settings().group(CompatItemGroup.addons)), Registry.BLOCK.getId(TraverseBlocks.LARGE_TRAVERSE_SNOWY_CONIFEROUS_FOREST_FERN));
    public static final Item TRAVERSE_SNOWY_CONIFEROUS_FOREST_SUGAR_CANE = ARFOItems.createItem(new BlockItem(TraverseBlocks.TRAVERSE_SNOWY_CONIFEROUS_FOREST_SUGAR_CANE, new Item.Settings().group(CompatItemGroup.addons)), Registry.BLOCK.getId(TraverseBlocks.TRAVERSE_SNOWY_CONIFEROUS_FOREST_SUGAR_CANE));
    public static final Item TRAVERSE_SNOWY_CONIFEROUS_FOREST_VINE = ARFOItems.createItem(new BlockItem(TraverseBlocks.TRAVERSE_SNOWY_CONIFEROUS_FOREST_VINE, new Item.Settings().group(CompatItemGroup.addons)), Registry.BLOCK.getId(TraverseBlocks.TRAVERSE_SNOWY_CONIFEROUS_FOREST_VINE));

    public static final Item TRAVERSE_MEADOW_GRASS_BLOCK = ARFOItems.createItem(new BlockItem(TraverseBlocks.TRAVERSE_MEADOW_GRASS_BLOCK, new Item.Settings().group(CompatItemGroup.addons)), Registry.BLOCK.getId(TraverseBlocks.TRAVERSE_MEADOW_GRASS_BLOCK));
    public static final Item TRAVERSE_MEADOW_GRASS_SLAB = ARFOItems.createItem(new BlockItem(TraverseBlocks.TRAVERSE_MEADOW_GRASS_SLAB, new Item.Settings().group(CompatItemGroup.addons)), Registry.BLOCK.getId(TraverseBlocks.TRAVERSE_MEADOW_GRASS_SLAB));
    public static final Item GLOWING_TRAVERSE_MEADOW_GRASS_BLOCK = ARFOItems.createItem(new BlockItem(TraverseBlocks.GLOWING_TRAVERSE_MEADOW_GRASS_BLOCK, new Item.Settings().group(CompatItemGroup.addons)), Registry.BLOCK.getId(TraverseBlocks.GLOWING_TRAVERSE_MEADOW_GRASS_BLOCK));
    public static final Item TRAVERSE_MEADOW_JUNGLE_LEAVES = ARFOItems.createItem(new BlockItem(TraverseBlocks.TRAVERSE_MEADOW_JUNGLE_LEAVES, new Item.Settings().group(CompatItemGroup.addons)), Registry.BLOCK.getId(TraverseBlocks.TRAVERSE_MEADOW_JUNGLE_LEAVES));
    public static final Item TRAVERSE_MEADOW_JUNGLE_LEAVES_CARPET = ARFOItems.createItem(new BlockItem(TraverseBlocks.TRAVERSE_MEADOW_JUNGLE_LEAVES_CARPET, new Item.Settings().group(CompatItemGroup.addons)), Registry.BLOCK.getId(TraverseBlocks.TRAVERSE_MEADOW_JUNGLE_LEAVES_CARPET));
    public static final Item TRAVERSE_MEADOW_OAK_LEAVES = ARFOItems.createItem(new BlockItem(TraverseBlocks.TRAVERSE_MEADOW_OAK_LEAVES, new Item.Settings().group(CompatItemGroup.addons)), Registry.BLOCK.getId(TraverseBlocks.TRAVERSE_MEADOW_OAK_LEAVES));
    public static final Item TRAVERSE_MEADOW_OAK_LEAVES_CARPET = ARFOItems.createItem(new BlockItem(TraverseBlocks.TRAVERSE_MEADOW_OAK_LEAVES_CARPET, new Item.Settings().group(CompatItemGroup.addons)), Registry.BLOCK.getId(TraverseBlocks.TRAVERSE_MEADOW_OAK_LEAVES_CARPET));
    public static final Item TRAVERSE_MEADOW_DARK_OAK_LEAVES = ARFOItems.createItem(new BlockItem(TraverseBlocks.TRAVERSE_MEADOW_DARK_OAK_LEAVES, new Item.Settings().group(CompatItemGroup.addons)), Registry.BLOCK.getId(TraverseBlocks.TRAVERSE_MEADOW_DARK_OAK_LEAVES));
    public static final Item TRAVERSE_MEADOW_DARK_OAK_LEAVES_CARPET = ARFOItems.createItem(new BlockItem(TraverseBlocks.TRAVERSE_MEADOW_DARK_OAK_LEAVES_CARPET, new Item.Settings().group(CompatItemGroup.addons)), Registry.BLOCK.getId(TraverseBlocks.TRAVERSE_MEADOW_DARK_OAK_LEAVES_CARPET));
    public static final Item TRAVERSE_MEADOW_ACACIA_LEAVES = ARFOItems.createItem(new BlockItem(TraverseBlocks.TRAVERSE_MEADOW_ACACIA_LEAVES, new Item.Settings().group(CompatItemGroup.addons)), Registry.BLOCK.getId(TraverseBlocks.TRAVERSE_MEADOW_ACACIA_LEAVES));
    public static final Item TRAVERSE_MEADOW_ACACIA_LEAVES_CARPET = ARFOItems.createItem(new BlockItem(TraverseBlocks.TRAVERSE_MEADOW_ACACIA_LEAVES_CARPET, new Item.Settings().group(CompatItemGroup.addons)), Registry.BLOCK.getId(TraverseBlocks.TRAVERSE_MEADOW_ACACIA_LEAVES_CARPET));
    public static final Item TRAVERSE_MEADOW_GRASS = ARFOItems.createItem(new BlockItem(TraverseBlocks.TRAVERSE_MEADOW_GRASS, new Item.Settings().group(CompatItemGroup.addons)), Registry.BLOCK.getId(TraverseBlocks.TRAVERSE_MEADOW_GRASS));
    public static final Item TALL_TRAVERSE_MEADOW_GRASS = ARFOItems.createItem(new BlockItem(TraverseBlocks.TALL_TRAVERSE_MEADOW_GRASS, new Item.Settings().group(CompatItemGroup.addons)), Registry.BLOCK.getId(TraverseBlocks.TALL_TRAVERSE_MEADOW_GRASS));
    public static final Item TRAVERSE_MEADOW_FERN = ARFOItems.createItem(new BlockItem(TraverseBlocks.TRAVERSE_MEADOW_FERN, new Item.Settings().group(CompatItemGroup.addons)), Registry.BLOCK.getId(TraverseBlocks.TRAVERSE_MEADOW_FERN));
    public static final Item LARGE_TRAVERSE_MEADOW_FERN = ARFOItems.createItem(new BlockItem(TraverseBlocks.LARGE_TRAVERSE_MEADOW_FERN, new Item.Settings().group(CompatItemGroup.addons)), Registry.BLOCK.getId(TraverseBlocks.LARGE_TRAVERSE_MEADOW_FERN));
    public static final Item TRAVERSE_MEADOW_SUGAR_CANE = ARFOItems.createItem(new BlockItem(TraverseBlocks.TRAVERSE_MEADOW_SUGAR_CANE, new Item.Settings().group(CompatItemGroup.addons)), Registry.BLOCK.getId(TraverseBlocks.TRAVERSE_MEADOW_SUGAR_CANE));
    public static final Item TRAVERSE_MEADOW_VINE = ARFOItems.createItem(new BlockItem(TraverseBlocks.TRAVERSE_MEADOW_VINE, new Item.Settings().group(CompatItemGroup.addons)), Registry.BLOCK.getId(TraverseBlocks.TRAVERSE_MEADOW_VINE));

    public static final Item TRAVERSE_LUSH_SWAMP_GRASS_BLOCK = ARFOItems.createItem(new BlockItem(TraverseBlocks.TRAVERSE_LUSH_SWAMP_GRASS_BLOCK, new Item.Settings().group(CompatItemGroup.addons)), Registry.BLOCK.getId(TraverseBlocks.TRAVERSE_LUSH_SWAMP_GRASS_BLOCK));
    public static final Item TRAVERSE_LUSH_SWAMP_GRASS_SLAB = ARFOItems.createItem(new BlockItem(TraverseBlocks.TRAVERSE_LUSH_SWAMP_GRASS_SLAB, new Item.Settings().group(CompatItemGroup.addons)), Registry.BLOCK.getId(TraverseBlocks.TRAVERSE_LUSH_SWAMP_GRASS_SLAB));
    public static final Item GLOWING_TRAVERSE_LUSH_SWAMP_GRASS_BLOCK = ARFOItems.createItem(new BlockItem(TraverseBlocks.GLOWING_TRAVERSE_LUSH_SWAMP_GRASS_BLOCK, new Item.Settings().group(CompatItemGroup.addons)), Registry.BLOCK.getId(TraverseBlocks.GLOWING_TRAVERSE_LUSH_SWAMP_GRASS_BLOCK));
    public static final Item TRAVERSE_LUSH_SWAMP_JUNGLE_LEAVES = ARFOItems.createItem(new BlockItem(TraverseBlocks.TRAVERSE_LUSH_SWAMP_JUNGLE_LEAVES, new Item.Settings().group(CompatItemGroup.addons)), Registry.BLOCK.getId(TraverseBlocks.TRAVERSE_LUSH_SWAMP_JUNGLE_LEAVES));
    public static final Item TRAVERSE_LUSH_SWAMP_JUNGLE_LEAVES_CARPET = ARFOItems.createItem(new BlockItem(TraverseBlocks.TRAVERSE_LUSH_SWAMP_JUNGLE_LEAVES_CARPET, new Item.Settings().group(CompatItemGroup.addons)), Registry.BLOCK.getId(TraverseBlocks.TRAVERSE_LUSH_SWAMP_JUNGLE_LEAVES_CARPET));
    public static final Item TRAVERSE_LUSH_SWAMP_OAK_LEAVES = ARFOItems.createItem(new BlockItem(TraverseBlocks.TRAVERSE_LUSH_SWAMP_OAK_LEAVES, new Item.Settings().group(CompatItemGroup.addons)), Registry.BLOCK.getId(TraverseBlocks.TRAVERSE_LUSH_SWAMP_OAK_LEAVES));
    public static final Item TRAVERSE_LUSH_SWAMP_OAK_LEAVES_CARPET = ARFOItems.createItem(new BlockItem(TraverseBlocks.TRAVERSE_LUSH_SWAMP_OAK_LEAVES_CARPET, new Item.Settings().group(CompatItemGroup.addons)), Registry.BLOCK.getId(TraverseBlocks.TRAVERSE_LUSH_SWAMP_OAK_LEAVES_CARPET));
    public static final Item TRAVERSE_LUSH_SWAMP_DARK_OAK_LEAVES = ARFOItems.createItem(new BlockItem(TraverseBlocks.TRAVERSE_LUSH_SWAMP_DARK_OAK_LEAVES, new Item.Settings().group(CompatItemGroup.addons)), Registry.BLOCK.getId(TraverseBlocks.TRAVERSE_LUSH_SWAMP_DARK_OAK_LEAVES));
    public static final Item TRAVERSE_LUSH_SWAMP_DARK_OAK_LEAVES_CARPET = ARFOItems.createItem(new BlockItem(TraverseBlocks.TRAVERSE_LUSH_SWAMP_DARK_OAK_LEAVES_CARPET, new Item.Settings().group(CompatItemGroup.addons)), Registry.BLOCK.getId(TraverseBlocks.TRAVERSE_LUSH_SWAMP_DARK_OAK_LEAVES_CARPET));
    public static final Item TRAVERSE_LUSH_SWAMP_ACACIA_LEAVES = ARFOItems.createItem(new BlockItem(TraverseBlocks.TRAVERSE_LUSH_SWAMP_ACACIA_LEAVES, new Item.Settings().group(CompatItemGroup.addons)), Registry.BLOCK.getId(TraverseBlocks.TRAVERSE_LUSH_SWAMP_ACACIA_LEAVES));
    public static final Item TRAVERSE_LUSH_SWAMP_ACACIA_LEAVES_CARPET = ARFOItems.createItem(new BlockItem(TraverseBlocks.TRAVERSE_LUSH_SWAMP_ACACIA_LEAVES_CARPET, new Item.Settings().group(CompatItemGroup.addons)), Registry.BLOCK.getId(TraverseBlocks.TRAVERSE_LUSH_SWAMP_ACACIA_LEAVES_CARPET));
    public static final Item TRAVERSE_LUSH_SWAMP_GRASS = ARFOItems.createItem(new BlockItem(TraverseBlocks.TRAVERSE_LUSH_SWAMP_GRASS, new Item.Settings().group(CompatItemGroup.addons)), Registry.BLOCK.getId(TraverseBlocks.TRAVERSE_LUSH_SWAMP_GRASS));
    public static final Item TALL_TRAVERSE_LUSH_SWAMP_GRASS = ARFOItems.createItem(new BlockItem(TraverseBlocks.TALL_TRAVERSE_LUSH_SWAMP_GRASS, new Item.Settings().group(CompatItemGroup.addons)), Registry.BLOCK.getId(TraverseBlocks.TALL_TRAVERSE_LUSH_SWAMP_GRASS));
    public static final Item TRAVERSE_LUSH_SWAMP_FERN = ARFOItems.createItem(new BlockItem(TraverseBlocks.TRAVERSE_LUSH_SWAMP_FERN, new Item.Settings().group(CompatItemGroup.addons)), Registry.BLOCK.getId(TraverseBlocks.TRAVERSE_LUSH_SWAMP_FERN));
    public static final Item LARGE_TRAVERSE_LUSH_SWAMP_FERN = ARFOItems.createItem(new BlockItem(TraverseBlocks.LARGE_TRAVERSE_LUSH_SWAMP_FERN, new Item.Settings().group(CompatItemGroup.addons)), Registry.BLOCK.getId(TraverseBlocks.LARGE_TRAVERSE_LUSH_SWAMP_FERN));
    public static final Item TRAVERSE_LUSH_SWAMP_SUGAR_CANE = ARFOItems.createItem(new BlockItem(TraverseBlocks.TRAVERSE_LUSH_SWAMP_SUGAR_CANE, new Item.Settings().group(CompatItemGroup.addons)), Registry.BLOCK.getId(TraverseBlocks.TRAVERSE_LUSH_SWAMP_SUGAR_CANE));
    public static final Item TRAVERSE_LUSH_SWAMP_VINE = ARFOItems.createItem(new BlockItem(TraverseBlocks.TRAVERSE_LUSH_SWAMP_VINE, new Item.Settings().group(CompatItemGroup.addons)), Registry.BLOCK.getId(TraverseBlocks.TRAVERSE_LUSH_SWAMP_VINE));

    public static final Item TRAVERSE_PLAINS_PLATEAU_GRASS_BLOCK = ARFOItems.createItem(new BlockItem(TraverseBlocks.TRAVERSE_PLAINS_PLATEAU_GRASS_BLOCK, new Item.Settings().group(CompatItemGroup.addons)), Registry.BLOCK.getId(TraverseBlocks.TRAVERSE_PLAINS_PLATEAU_GRASS_BLOCK));
    public static final Item TRAVERSE_PLAINS_PLATEAU_GRASS_SLAB = ARFOItems.createItem(new BlockItem(TraverseBlocks.TRAVERSE_PLAINS_PLATEAU_GRASS_SLAB, new Item.Settings().group(CompatItemGroup.addons)), Registry.BLOCK.getId(TraverseBlocks.TRAVERSE_PLAINS_PLATEAU_GRASS_SLAB));
    public static final Item GLOWING_TRAVERSE_PLAINS_PLATEAU_GRASS_BLOCK = ARFOItems.createItem(new BlockItem(TraverseBlocks.GLOWING_TRAVERSE_PLAINS_PLATEAU_GRASS_BLOCK, new Item.Settings().group(CompatItemGroup.addons)), Registry.BLOCK.getId(TraverseBlocks.GLOWING_TRAVERSE_PLAINS_PLATEAU_GRASS_BLOCK));
    public static final Item TRAVERSE_PLAINS_PLATEAU_JUNGLE_LEAVES = ARFOItems.createItem(new BlockItem(TraverseBlocks.TRAVERSE_PLAINS_PLATEAU_JUNGLE_LEAVES, new Item.Settings().group(CompatItemGroup.addons)), Registry.BLOCK.getId(TraverseBlocks.TRAVERSE_PLAINS_PLATEAU_JUNGLE_LEAVES));
    public static final Item TRAVERSE_PLAINS_PLATEAU_JUNGLE_LEAVES_CARPET = ARFOItems.createItem(new BlockItem(TraverseBlocks.TRAVERSE_PLAINS_PLATEAU_JUNGLE_LEAVES_CARPET, new Item.Settings().group(CompatItemGroup.addons)), Registry.BLOCK.getId(TraverseBlocks.TRAVERSE_PLAINS_PLATEAU_JUNGLE_LEAVES_CARPET));
    public static final Item TRAVERSE_PLAINS_PLATEAU_OAK_LEAVES = ARFOItems.createItem(new BlockItem(TraverseBlocks.TRAVERSE_PLAINS_PLATEAU_OAK_LEAVES, new Item.Settings().group(CompatItemGroup.addons)), Registry.BLOCK.getId(TraverseBlocks.TRAVERSE_PLAINS_PLATEAU_OAK_LEAVES));
    public static final Item TRAVERSE_PLAINS_PLATEAU_OAK_LEAVES_CARPET = ARFOItems.createItem(new BlockItem(TraverseBlocks.TRAVERSE_PLAINS_PLATEAU_OAK_LEAVES_CARPET, new Item.Settings().group(CompatItemGroup.addons)), Registry.BLOCK.getId(TraverseBlocks.TRAVERSE_PLAINS_PLATEAU_OAK_LEAVES_CARPET));
    public static final Item TRAVERSE_PLAINS_PLATEAU_DARK_OAK_LEAVES = ARFOItems.createItem(new BlockItem(TraverseBlocks.TRAVERSE_PLAINS_PLATEAU_DARK_OAK_LEAVES, new Item.Settings().group(CompatItemGroup.addons)), Registry.BLOCK.getId(TraverseBlocks.TRAVERSE_PLAINS_PLATEAU_DARK_OAK_LEAVES));
    public static final Item TRAVERSE_PLAINS_PLATEAU_DARK_OAK_LEAVES_CARPET = ARFOItems.createItem(new BlockItem(TraverseBlocks.TRAVERSE_PLAINS_PLATEAU_DARK_OAK_LEAVES_CARPET, new Item.Settings().group(CompatItemGroup.addons)), Registry.BLOCK.getId(TraverseBlocks.TRAVERSE_PLAINS_PLATEAU_DARK_OAK_LEAVES_CARPET));
    public static final Item TRAVERSE_PLAINS_PLATEAU_ACACIA_LEAVES = ARFOItems.createItem(new BlockItem(TraverseBlocks.TRAVERSE_PLAINS_PLATEAU_ACACIA_LEAVES, new Item.Settings().group(CompatItemGroup.addons)), Registry.BLOCK.getId(TraverseBlocks.TRAVERSE_PLAINS_PLATEAU_ACACIA_LEAVES));
    public static final Item TRAVERSE_PLAINS_PLATEAU_ACACIA_LEAVES_CARPET = ARFOItems.createItem(new BlockItem(TraverseBlocks.TRAVERSE_PLAINS_PLATEAU_ACACIA_LEAVES_CARPET, new Item.Settings().group(CompatItemGroup.addons)), Registry.BLOCK.getId(TraverseBlocks.TRAVERSE_PLAINS_PLATEAU_ACACIA_LEAVES_CARPET));
    public static final Item TRAVERSE_PLAINS_PLATEAU_GRASS = ARFOItems.createItem(new BlockItem(TraverseBlocks.TRAVERSE_PLAINS_PLATEAU_GRASS, new Item.Settings().group(CompatItemGroup.addons)), Registry.BLOCK.getId(TraverseBlocks.TRAVERSE_PLAINS_PLATEAU_GRASS));
    public static final Item TALL_TRAVERSE_PLAINS_PLATEAU_GRASS = ARFOItems.createItem(new BlockItem(TraverseBlocks.TALL_TRAVERSE_PLAINS_PLATEAU_GRASS, new Item.Settings().group(CompatItemGroup.addons)), Registry.BLOCK.getId(TraverseBlocks.TALL_TRAVERSE_PLAINS_PLATEAU_GRASS));
    public static final Item TRAVERSE_PLAINS_PLATEAU_FERN = ARFOItems.createItem(new BlockItem(TraverseBlocks.TRAVERSE_PLAINS_PLATEAU_FERN, new Item.Settings().group(CompatItemGroup.addons)), Registry.BLOCK.getId(TraverseBlocks.TRAVERSE_PLAINS_PLATEAU_FERN));
    public static final Item LARGE_TRAVERSE_PLAINS_PLATEAU_FERN = ARFOItems.createItem(new BlockItem(TraverseBlocks.LARGE_TRAVERSE_PLAINS_PLATEAU_FERN, new Item.Settings().group(CompatItemGroup.addons)), Registry.BLOCK.getId(TraverseBlocks.LARGE_TRAVERSE_PLAINS_PLATEAU_FERN));
    public static final Item TRAVERSE_PLAINS_PLATEAU_SUGAR_CANE = ARFOItems.createItem(new BlockItem(TraverseBlocks.TRAVERSE_PLAINS_PLATEAU_SUGAR_CANE, new Item.Settings().group(CompatItemGroup.addons)), Registry.BLOCK.getId(TraverseBlocks.TRAVERSE_PLAINS_PLATEAU_SUGAR_CANE));
    public static final Item TRAVERSE_PLAINS_PLATEAU_VINE = ARFOItems.createItem(new BlockItem(TraverseBlocks.TRAVERSE_PLAINS_PLATEAU_VINE, new Item.Settings().group(CompatItemGroup.addons)), Registry.BLOCK.getId(TraverseBlocks.TRAVERSE_PLAINS_PLATEAU_VINE));

    public static final Item TRAVERSE_ROLLING_HILLS_GRASS_BLOCK = ARFOItems.createItem(new BlockItem(TraverseBlocks.TRAVERSE_ROLLING_HILLS_GRASS_BLOCK, new Item.Settings().group(CompatItemGroup.addons)), Registry.BLOCK.getId(TraverseBlocks.TRAVERSE_ROLLING_HILLS_GRASS_BLOCK));
    public static final Item TRAVERSE_ROLLING_HILLS_GRASS_SLAB = ARFOItems.createItem(new BlockItem(TraverseBlocks.TRAVERSE_ROLLING_HILLS_GRASS_SLAB, new Item.Settings().group(CompatItemGroup.addons)), Registry.BLOCK.getId(TraverseBlocks.TRAVERSE_ROLLING_HILLS_GRASS_SLAB));
    public static final Item GLOWING_TRAVERSE_ROLLING_HILLS_GRASS_BLOCK = ARFOItems.createItem(new BlockItem(TraverseBlocks.GLOWING_TRAVERSE_ROLLING_HILLS_GRASS_BLOCK, new Item.Settings().group(CompatItemGroup.addons)), Registry.BLOCK.getId(TraverseBlocks.GLOWING_TRAVERSE_ROLLING_HILLS_GRASS_BLOCK));
    public static final Item TRAVERSE_ROLLING_HILLS_JUNGLE_LEAVES = ARFOItems.createItem(new BlockItem(TraverseBlocks.TRAVERSE_ROLLING_HILLS_JUNGLE_LEAVES, new Item.Settings().group(CompatItemGroup.addons)), Registry.BLOCK.getId(TraverseBlocks.TRAVERSE_ROLLING_HILLS_JUNGLE_LEAVES));
    public static final Item TRAVERSE_ROLLING_HILLS_JUNGLE_LEAVES_CARPET = ARFOItems.createItem(new BlockItem(TraverseBlocks.TRAVERSE_ROLLING_HILLS_JUNGLE_LEAVES_CARPET, new Item.Settings().group(CompatItemGroup.addons)), Registry.BLOCK.getId(TraverseBlocks.TRAVERSE_ROLLING_HILLS_JUNGLE_LEAVES_CARPET));
    public static final Item TRAVERSE_ROLLING_HILLS_OAK_LEAVES = ARFOItems.createItem(new BlockItem(TraverseBlocks.TRAVERSE_ROLLING_HILLS_OAK_LEAVES, new Item.Settings().group(CompatItemGroup.addons)), Registry.BLOCK.getId(TraverseBlocks.TRAVERSE_ROLLING_HILLS_OAK_LEAVES));
    public static final Item TRAVERSE_ROLLING_HILLS_OAK_LEAVES_CARPET = ARFOItems.createItem(new BlockItem(TraverseBlocks.TRAVERSE_ROLLING_HILLS_OAK_LEAVES_CARPET, new Item.Settings().group(CompatItemGroup.addons)), Registry.BLOCK.getId(TraverseBlocks.TRAVERSE_ROLLING_HILLS_OAK_LEAVES_CARPET));
    public static final Item TRAVERSE_ROLLING_HILLS_DARK_OAK_LEAVES = ARFOItems.createItem(new BlockItem(TraverseBlocks.TRAVERSE_ROLLING_HILLS_DARK_OAK_LEAVES, new Item.Settings().group(CompatItemGroup.addons)), Registry.BLOCK.getId(TraverseBlocks.TRAVERSE_ROLLING_HILLS_DARK_OAK_LEAVES));
    public static final Item TRAVERSE_ROLLING_HILLS_DARK_OAK_LEAVES_CARPET = ARFOItems.createItem(new BlockItem(TraverseBlocks.TRAVERSE_ROLLING_HILLS_DARK_OAK_LEAVES_CARPET, new Item.Settings().group(CompatItemGroup.addons)), Registry.BLOCK.getId(TraverseBlocks.TRAVERSE_ROLLING_HILLS_DARK_OAK_LEAVES_CARPET));
    public static final Item TRAVERSE_ROLLING_HILLS_ACACIA_LEAVES = ARFOItems.createItem(new BlockItem(TraverseBlocks.TRAVERSE_ROLLING_HILLS_ACACIA_LEAVES, new Item.Settings().group(CompatItemGroup.addons)), Registry.BLOCK.getId(TraverseBlocks.TRAVERSE_ROLLING_HILLS_ACACIA_LEAVES));
    public static final Item TRAVERSE_ROLLING_HILLS_ACACIA_LEAVES_CARPET = ARFOItems.createItem(new BlockItem(TraverseBlocks.TRAVERSE_ROLLING_HILLS_ACACIA_LEAVES_CARPET, new Item.Settings().group(CompatItemGroup.addons)), Registry.BLOCK.getId(TraverseBlocks.TRAVERSE_ROLLING_HILLS_ACACIA_LEAVES_CARPET));
    public static final Item TRAVERSE_ROLLING_HILLS_GRASS = ARFOItems.createItem(new BlockItem(TraverseBlocks.TRAVERSE_ROLLING_HILLS_GRASS, new Item.Settings().group(CompatItemGroup.addons)), Registry.BLOCK.getId(TraverseBlocks.TRAVERSE_ROLLING_HILLS_GRASS));
    public static final Item TALL_TRAVERSE_ROLLING_HILLS_GRASS = ARFOItems.createItem(new BlockItem(TraverseBlocks.TALL_TRAVERSE_ROLLING_HILLS_GRASS, new Item.Settings().group(CompatItemGroup.addons)), Registry.BLOCK.getId(TraverseBlocks.TALL_TRAVERSE_ROLLING_HILLS_GRASS));
    public static final Item TRAVERSE_ROLLING_HILLS_FERN = ARFOItems.createItem(new BlockItem(TraverseBlocks.TRAVERSE_ROLLING_HILLS_FERN, new Item.Settings().group(CompatItemGroup.addons)), Registry.BLOCK.getId(TraverseBlocks.TRAVERSE_ROLLING_HILLS_FERN));
    public static final Item LARGE_TRAVERSE_ROLLING_HILLS_FERN = ARFOItems.createItem(new BlockItem(TraverseBlocks.LARGE_TRAVERSE_ROLLING_HILLS_FERN, new Item.Settings().group(CompatItemGroup.addons)), Registry.BLOCK.getId(TraverseBlocks.LARGE_TRAVERSE_ROLLING_HILLS_FERN));
    public static final Item TRAVERSE_ROLLING_HILLS_SUGAR_CANE = ARFOItems.createItem(new BlockItem(TraverseBlocks.TRAVERSE_ROLLING_HILLS_SUGAR_CANE, new Item.Settings().group(CompatItemGroup.addons)), Registry.BLOCK.getId(TraverseBlocks.TRAVERSE_ROLLING_HILLS_SUGAR_CANE));
    public static final Item TRAVERSE_ROLLING_HILLS_VINE = ARFOItems.createItem(new BlockItem(TraverseBlocks.TRAVERSE_ROLLING_HILLS_VINE, new Item.Settings().group(CompatItemGroup.addons)), Registry.BLOCK.getId(TraverseBlocks.TRAVERSE_ROLLING_HILLS_VINE));

    public static final Item TRAVERSE_WOODED_ISLAND_GRASS_BLOCK = ARFOItems.createItem(new BlockItem(TraverseBlocks.TRAVERSE_WOODED_ISLAND_GRASS_BLOCK, new Item.Settings().group(CompatItemGroup.addons)), Registry.BLOCK.getId(TraverseBlocks.TRAVERSE_WOODED_ISLAND_GRASS_BLOCK));
    public static final Item TRAVERSE_WOODED_ISLAND_GRASS_SLAB = ARFOItems.createItem(new BlockItem(TraverseBlocks.TRAVERSE_WOODED_ISLAND_GRASS_SLAB, new Item.Settings().group(CompatItemGroup.addons)), Registry.BLOCK.getId(TraverseBlocks.TRAVERSE_WOODED_ISLAND_GRASS_SLAB));
    public static final Item GLOWING_TRAVERSE_WOODED_ISLAND_GRASS_BLOCK = ARFOItems.createItem(new BlockItem(TraverseBlocks.GLOWING_TRAVERSE_WOODED_ISLAND_GRASS_BLOCK, new Item.Settings().group(CompatItemGroup.addons)), Registry.BLOCK.getId(TraverseBlocks.GLOWING_TRAVERSE_WOODED_ISLAND_GRASS_BLOCK));
    public static final Item TRAVERSE_WOODED_ISLAND_JUNGLE_LEAVES = ARFOItems.createItem(new BlockItem(TraverseBlocks.TRAVERSE_WOODED_ISLAND_JUNGLE_LEAVES, new Item.Settings().group(CompatItemGroup.addons)), Registry.BLOCK.getId(TraverseBlocks.TRAVERSE_WOODED_ISLAND_JUNGLE_LEAVES));
    public static final Item TRAVERSE_WOODED_ISLAND_JUNGLE_LEAVES_CARPET = ARFOItems.createItem(new BlockItem(TraverseBlocks.TRAVERSE_WOODED_ISLAND_JUNGLE_LEAVES_CARPET, new Item.Settings().group(CompatItemGroup.addons)), Registry.BLOCK.getId(TraverseBlocks.TRAVERSE_WOODED_ISLAND_JUNGLE_LEAVES_CARPET));
    public static final Item TRAVERSE_WOODED_ISLAND_OAK_LEAVES = ARFOItems.createItem(new BlockItem(TraverseBlocks.TRAVERSE_WOODED_ISLAND_OAK_LEAVES, new Item.Settings().group(CompatItemGroup.addons)), Registry.BLOCK.getId(TraverseBlocks.TRAVERSE_WOODED_ISLAND_OAK_LEAVES));
    public static final Item TRAVERSE_WOODED_ISLAND_OAK_LEAVES_CARPET = ARFOItems.createItem(new BlockItem(TraverseBlocks.TRAVERSE_WOODED_ISLAND_OAK_LEAVES_CARPET, new Item.Settings().group(CompatItemGroup.addons)), Registry.BLOCK.getId(TraverseBlocks.TRAVERSE_WOODED_ISLAND_OAK_LEAVES_CARPET));
    public static final Item TRAVERSE_WOODED_ISLAND_DARK_OAK_LEAVES = ARFOItems.createItem(new BlockItem(TraverseBlocks.TRAVERSE_WOODED_ISLAND_DARK_OAK_LEAVES, new Item.Settings().group(CompatItemGroup.addons)), Registry.BLOCK.getId(TraverseBlocks.TRAVERSE_WOODED_ISLAND_DARK_OAK_LEAVES));
    public static final Item TRAVERSE_WOODED_ISLAND_DARK_OAK_LEAVES_CARPET = ARFOItems.createItem(new BlockItem(TraverseBlocks.TRAVERSE_WOODED_ISLAND_DARK_OAK_LEAVES_CARPET, new Item.Settings().group(CompatItemGroup.addons)), Registry.BLOCK.getId(TraverseBlocks.TRAVERSE_WOODED_ISLAND_DARK_OAK_LEAVES_CARPET));
    public static final Item TRAVERSE_WOODED_ISLAND_ACACIA_LEAVES = ARFOItems.createItem(new BlockItem(TraverseBlocks.TRAVERSE_WOODED_ISLAND_ACACIA_LEAVES, new Item.Settings().group(CompatItemGroup.addons)), Registry.BLOCK.getId(TraverseBlocks.TRAVERSE_WOODED_ISLAND_ACACIA_LEAVES));
    public static final Item TRAVERSE_WOODED_ISLAND_ACACIA_LEAVES_CARPET = ARFOItems.createItem(new BlockItem(TraverseBlocks.TRAVERSE_WOODED_ISLAND_ACACIA_LEAVES_CARPET, new Item.Settings().group(CompatItemGroup.addons)), Registry.BLOCK.getId(TraverseBlocks.TRAVERSE_WOODED_ISLAND_ACACIA_LEAVES_CARPET));
    public static final Item TRAVERSE_WOODED_ISLAND_GRASS = ARFOItems.createItem(new BlockItem(TraverseBlocks.TRAVERSE_WOODED_ISLAND_GRASS, new Item.Settings().group(CompatItemGroup.addons)), Registry.BLOCK.getId(TraverseBlocks.TRAVERSE_WOODED_ISLAND_GRASS));
    public static final Item TALL_TRAVERSE_WOODED_ISLAND_GRASS = ARFOItems.createItem(new BlockItem(TraverseBlocks.TALL_TRAVERSE_WOODED_ISLAND_GRASS, new Item.Settings().group(CompatItemGroup.addons)), Registry.BLOCK.getId(TraverseBlocks.TALL_TRAVERSE_WOODED_ISLAND_GRASS));
    public static final Item TRAVERSE_WOODED_ISLAND_FERN = ARFOItems.createItem(new BlockItem(TraverseBlocks.TRAVERSE_WOODED_ISLAND_FERN, new Item.Settings().group(CompatItemGroup.addons)), Registry.BLOCK.getId(TraverseBlocks.TRAVERSE_WOODED_ISLAND_FERN));
    public static final Item LARGE_TRAVERSE_WOODED_ISLAND_FERN = ARFOItems.createItem(new BlockItem(TraverseBlocks.LARGE_TRAVERSE_WOODED_ISLAND_FERN, new Item.Settings().group(CompatItemGroup.addons)), Registry.BLOCK.getId(TraverseBlocks.LARGE_TRAVERSE_WOODED_ISLAND_FERN));
    public static final Item TRAVERSE_WOODED_ISLAND_SUGAR_CANE = ARFOItems.createItem(new BlockItem(TraverseBlocks.TRAVERSE_WOODED_ISLAND_SUGAR_CANE, new Item.Settings().group(CompatItemGroup.addons)), Registry.BLOCK.getId(TraverseBlocks.TRAVERSE_WOODED_ISLAND_SUGAR_CANE));
    public static final Item TRAVERSE_WOODED_ISLAND_VINE = ARFOItems.createItem(new BlockItem(TraverseBlocks.TRAVERSE_WOODED_ISLAND_VINE, new Item.Settings().group(CompatItemGroup.addons)), Registry.BLOCK.getId(TraverseBlocks.TRAVERSE_WOODED_ISLAND_VINE));

    public static final Item TRAVERSE_WOODLANDS_GRASS_BLOCK = ARFOItems.createItem(new BlockItem(TraverseBlocks.TRAVERSE_WOODLANDS_GRASS_BLOCK, new Item.Settings().group(CompatItemGroup.addons)), Registry.BLOCK.getId(TraverseBlocks.TRAVERSE_WOODLANDS_GRASS_BLOCK));
    public static final Item TRAVERSE_WOODLANDS_GRASS_SLAB = ARFOItems.createItem(new BlockItem(TraverseBlocks.TRAVERSE_WOODLANDS_GRASS_SLAB, new Item.Settings().group(CompatItemGroup.addons)), Registry.BLOCK.getId(TraverseBlocks.TRAVERSE_WOODLANDS_GRASS_SLAB));
    public static final Item GLOWING_TRAVERSE_WOODLANDS_GRASS_BLOCK = ARFOItems.createItem(new BlockItem(TraverseBlocks.GLOWING_TRAVERSE_WOODLANDS_GRASS_BLOCK, new Item.Settings().group(CompatItemGroup.addons)), Registry.BLOCK.getId(TraverseBlocks.GLOWING_TRAVERSE_WOODLANDS_GRASS_BLOCK));
    public static final Item TRAVERSE_WOODLANDS_JUNGLE_LEAVES = ARFOItems.createItem(new BlockItem(TraverseBlocks.TRAVERSE_WOODLANDS_JUNGLE_LEAVES, new Item.Settings().group(CompatItemGroup.addons)), Registry.BLOCK.getId(TraverseBlocks.TRAVERSE_WOODLANDS_JUNGLE_LEAVES));
    public static final Item TRAVERSE_WOODLANDS_JUNGLE_LEAVES_CARPET = ARFOItems.createItem(new BlockItem(TraverseBlocks.TRAVERSE_WOODLANDS_JUNGLE_LEAVES_CARPET, new Item.Settings().group(CompatItemGroup.addons)), Registry.BLOCK.getId(TraverseBlocks.TRAVERSE_WOODLANDS_JUNGLE_LEAVES_CARPET));
    public static final Item TRAVERSE_WOODLANDS_OAK_LEAVES = ARFOItems.createItem(new BlockItem(TraverseBlocks.TRAVERSE_WOODLANDS_OAK_LEAVES, new Item.Settings().group(CompatItemGroup.addons)), Registry.BLOCK.getId(TraverseBlocks.TRAVERSE_WOODLANDS_OAK_LEAVES));
    public static final Item TRAVERSE_WOODLANDS_OAK_LEAVES_CARPET = ARFOItems.createItem(new BlockItem(TraverseBlocks.TRAVERSE_WOODLANDS_OAK_LEAVES_CARPET, new Item.Settings().group(CompatItemGroup.addons)), Registry.BLOCK.getId(TraverseBlocks.TRAVERSE_WOODLANDS_OAK_LEAVES_CARPET));
    public static final Item TRAVERSE_WOODLANDS_DARK_OAK_LEAVES = ARFOItems.createItem(new BlockItem(TraverseBlocks.TRAVERSE_WOODLANDS_DARK_OAK_LEAVES, new Item.Settings().group(CompatItemGroup.addons)), Registry.BLOCK.getId(TraverseBlocks.TRAVERSE_WOODLANDS_DARK_OAK_LEAVES));
    public static final Item TRAVERSE_WOODLANDS_DARK_OAK_LEAVES_CARPET = ARFOItems.createItem(new BlockItem(TraverseBlocks.TRAVERSE_WOODLANDS_DARK_OAK_LEAVES_CARPET, new Item.Settings().group(CompatItemGroup.addons)), Registry.BLOCK.getId(TraverseBlocks.TRAVERSE_WOODLANDS_DARK_OAK_LEAVES_CARPET));
    public static final Item TRAVERSE_WOODLANDS_ACACIA_LEAVES = ARFOItems.createItem(new BlockItem(TraverseBlocks.TRAVERSE_WOODLANDS_ACACIA_LEAVES, new Item.Settings().group(CompatItemGroup.addons)), Registry.BLOCK.getId(TraverseBlocks.TRAVERSE_WOODLANDS_ACACIA_LEAVES));
    public static final Item TRAVERSE_WOODLANDS_ACACIA_LEAVES_CARPET = ARFOItems.createItem(new BlockItem(TraverseBlocks.TRAVERSE_WOODLANDS_ACACIA_LEAVES_CARPET, new Item.Settings().group(CompatItemGroup.addons)), Registry.BLOCK.getId(TraverseBlocks.TRAVERSE_WOODLANDS_ACACIA_LEAVES_CARPET));
    public static final Item TRAVERSE_WOODLANDS_GRASS = ARFOItems.createItem(new BlockItem(TraverseBlocks.TRAVERSE_WOODLANDS_GRASS, new Item.Settings().group(CompatItemGroup.addons)), Registry.BLOCK.getId(TraverseBlocks.TRAVERSE_WOODLANDS_GRASS));
    public static final Item TALL_TRAVERSE_WOODLANDS_GRASS = ARFOItems.createItem(new BlockItem(TraverseBlocks.TALL_TRAVERSE_WOODLANDS_GRASS, new Item.Settings().group(CompatItemGroup.addons)), Registry.BLOCK.getId(TraverseBlocks.TALL_TRAVERSE_WOODLANDS_GRASS));
    public static final Item TRAVERSE_WOODLANDS_FERN = ARFOItems.createItem(new BlockItem(TraverseBlocks.TRAVERSE_WOODLANDS_FERN, new Item.Settings().group(CompatItemGroup.addons)), Registry.BLOCK.getId(TraverseBlocks.TRAVERSE_WOODLANDS_FERN));
    public static final Item LARGE_TRAVERSE_WOODLANDS_FERN = ARFOItems.createItem(new BlockItem(TraverseBlocks.LARGE_TRAVERSE_WOODLANDS_FERN, new Item.Settings().group(CompatItemGroup.addons)), Registry.BLOCK.getId(TraverseBlocks.LARGE_TRAVERSE_WOODLANDS_FERN));
    public static final Item TRAVERSE_WOODLANDS_SUGAR_CANE = ARFOItems.createItem(new BlockItem(TraverseBlocks.TRAVERSE_WOODLANDS_SUGAR_CANE, new Item.Settings().group(CompatItemGroup.addons)), Registry.BLOCK.getId(TraverseBlocks.TRAVERSE_WOODLANDS_SUGAR_CANE));
    public static final Item TRAVERSE_WOODLANDS_VINE = ARFOItems.createItem(new BlockItem(TraverseBlocks.TRAVERSE_WOODLANDS_VINE, new Item.Settings().group(CompatItemGroup.addons)), Registry.BLOCK.getId(TraverseBlocks.TRAVERSE_WOODLANDS_VINE));

    public static final Item TRAVERSE_RED_AUTUMNAL_LEAVES_CARPET = ARFOItems.createItem(new BlockItem(TraverseBlocks.TRAVERSE_RED_AUTUMNAL_LEAVES_CARPET, new Item.Settings().group(CompatItemGroup.addons)), Registry.BLOCK.getId(TraverseBlocks.TRAVERSE_RED_AUTUMNAL_LEAVES_CARPET));
    public static final Item TRAVERSE_YELLOW_AUTUMNAL_LEAVES_CARPET = ARFOItems.createItem(new BlockItem(TraverseBlocks.TRAVERSE_YELLOW_AUTUMNAL_LEAVES_CARPET, new Item.Settings().group(CompatItemGroup.addons)), Registry.BLOCK.getId(TraverseBlocks.TRAVERSE_YELLOW_AUTUMNAL_LEAVES_CARPET));
    public static final Item TRAVERSE_ORANGE_AUTUMNAL_LEAVES_CARPET = ARFOItems.createItem(new BlockItem(TraverseBlocks.TRAVERSE_ORANGE_AUTUMNAL_LEAVES_CARPET, new Item.Settings().group(CompatItemGroup.addons)), Registry.BLOCK.getId(TraverseBlocks.TRAVERSE_ORANGE_AUTUMNAL_LEAVES_CARPET));
    public static final Item TRAVERSE_BROWN_AUTUMNAL_LEAVES_CARPET = ARFOItems.createItem(new BlockItem(TraverseBlocks.TRAVERSE_BROWN_AUTUMNAL_LEAVES_CARPET, new Item.Settings().group(CompatItemGroup.addons)), Registry.BLOCK.getId(TraverseBlocks.TRAVERSE_BROWN_AUTUMNAL_LEAVES_CARPET));
    public static final Item TRAVERSE_DYE = ARFOItems.createItem(new ARFODyeItem(new Item.Settings().group(CompatItemGroup.addons)), "traverse_dye");

    public static final Item TRAVERSE_CLIFFS_WATER_BUCKET = ARFOItems.createItem(new BucketItem(TraverseFluids.STILL_TRAVERSE_CLIFFS_WATER, new Item.Settings().group(CompatItemGroup.addons)), "traverse_cliffs_water_bucket");
    public static final Item TRAVERSE_LUSH_SWAMP_WATER_BUCKET = ARFOItems.createItem(new BucketItem(TraverseFluids.STILL_TRAVERSE_LUSH_SWAMP_WATER, new Item.Settings().group(CompatItemGroup.addons)), "traverse_lush_swamp_water_bucket");
    public static final Item TRAVERSE_MINI_JUNGLE_WATER_BUCKET = ARFOItems.createItem(new BucketItem(TraverseFluids.STILL_TRAVERSE_MINI_JUNGLE_WATER, new Item.Settings().group(CompatItemGroup.addons)), "traverse_mini_jungle_water_bucket");




}
